package userinterface.TransplantCoordinatorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.OrganMatch;
import Business.Organization.Organization;
import Business.Requests.LogisticsRequest;
import Business.Statuses.RequestStatus;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class PreSurgeryCoordinationJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private OrganMatch organMatch;

    /**
     * Creates new form PreSurgeryCoordinationJPanel
     */
    public PreSurgeryCoordinationJPanel(JPanel userProcessContainer, EcoSystem business, OrganMatch organMatch) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.organMatch = organMatch;
        
        displayMatchDetails();
    }
    
    private void displayMatchDetails() {
        lblPatientName.setText(organMatch.getPatientRequest().getPatient().getName());
        lblDonorName.setText(organMatch.getDonorRequest().getDonor().getName());
        lblOrganType.setText(organMatch.getPatientRequest().getRequiredOrganType().getValue());
        lblMatchStatus.setText(organMatch.getStatus());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPatient = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblDonor = new javax.swing.JLabel();
        lblDonorName = new javax.swing.JLabel();
        lblOrgan = new javax.swing.JLabel();
        lblOrganType = new javax.swing.JLabel();
        lblMatchCurrentStatus = new javax.swing.JLabel();
        lblMatchStatus = new javax.swing.JLabel();
        lblDonorHospitalUpdates = new javax.swing.JLabel();
        chkMedicalClearance = new javax.swing.JCheckBox();
        lblRetrievalDate = new javax.swing.JLabel();
        txtRetrievalDate = new javax.swing.JTextField();
        lblRecipientHospitalConfirmations = new javax.swing.JLabel();
        chkRecipientPreparation = new javax.swing.JCheckBox();
        chkICUBed = new javax.swing.JCheckBox();
        lblTransportOptions = new javax.swing.JLabel();
        txtTransportOptions = new javax.swing.JTextField();
        chkDigitalAgreement = new javax.swing.JCheckBox();
        btnGenerateChecklist = new javax.swing.JButton();
        btnUpdateStatus = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 255, 204));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Pre-Surgery Coordination");

        lblPatient.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPatient.setForeground(new java.awt.Color(204, 255, 204));
        lblPatient.setText("Patient:");

        lblPatientName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPatientName.setForeground(new java.awt.Color(204, 255, 204));
        lblPatientName.setText("<Patient Name>");

        lblDonor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDonor.setForeground(new java.awt.Color(204, 255, 204));
        lblDonor.setText("Donor:");

        lblDonorName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDonorName.setForeground(new java.awt.Color(204, 255, 204));
        lblDonorName.setText("<Donor Name>");

        lblOrgan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOrgan.setForeground(new java.awt.Color(204, 255, 204));
        lblOrgan.setText("Organ:");

        lblOrganType.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblOrganType.setForeground(new java.awt.Color(204, 255, 204));
        lblOrganType.setText("<Organ Type>");

        lblMatchCurrentStatus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMatchCurrentStatus.setForeground(new java.awt.Color(204, 255, 204));
        lblMatchCurrentStatus.setText("Match Status:");

        lblMatchStatus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMatchStatus.setForeground(new java.awt.Color(204, 255, 204));
        lblMatchStatus.setText("<Match Status>");

        lblDonorHospitalUpdates.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblDonorHospitalUpdates.setForeground(new java.awt.Color(204, 255, 204));
        lblDonorHospitalUpdates.setText("Donor Hospital Updates:");

        chkMedicalClearance.setBackground(new java.awt.Color(0, 153, 153));
        chkMedicalClearance.setForeground(new java.awt.Color(204, 255, 204));
        chkMedicalClearance.setText("Final Medical Clearance Confirmed");

        lblRetrievalDate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblRetrievalDate.setForeground(new java.awt.Color(204, 255, 204));
        lblRetrievalDate.setText("Proposed Retrieval Date (YYYY-MM-DD):");

        lblRecipientHospitalConfirmations.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblRecipientHospitalConfirmations.setForeground(new java.awt.Color(204, 255, 204));
        lblRecipientHospitalConfirmations.setText("Recipient Hospital Confirmations:");

        chkRecipientPreparation.setBackground(new java.awt.Color(0, 153, 153));
        chkRecipientPreparation.setForeground(new java.awt.Color(204, 255, 204));
        chkRecipientPreparation.setText("Recipient Preparation Status Confirmed");

        chkICUBed.setBackground(new java.awt.Color(0, 153, 153));
        chkICUBed.setForeground(new java.awt.Color(204, 255, 204));
        chkICUBed.setText("Post-Op ICU Bed Reservation Confirmed");

        lblTransportOptions.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTransportOptions.setForeground(new java.awt.Color(204, 255, 204));
        lblTransportOptions.setText("Transport Options:");

        chkDigitalAgreement.setBackground(new java.awt.Color(0, 153, 153));
        chkDigitalAgreement.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        chkDigitalAgreement.setForeground(new java.awt.Color(204, 255, 204));
        chkDigitalAgreement.setText("Digital Surgical Coordination Agreement Signed");

        btnGenerateChecklist.setBackground(new java.awt.Color(0, 102, 102));
        btnGenerateChecklist.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGenerateChecklist.setForeground(new java.awt.Color(204, 255, 204));
        btnGenerateChecklist.setText("Generate Surgical Checklist");
        btnGenerateChecklist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateChecklistActionPerformed(evt);
            }
        });

        btnUpdateStatus.setBackground(new java.awt.Color(0, 102, 102));
        btnUpdateStatus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnUpdateStatus.setForeground(new java.awt.Color(204, 255, 204));
        btnUpdateStatus.setText("Update Coordination Status");
        btnUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStatusActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(204, 255, 204));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDonorHospitalUpdates)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPatient)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblDonor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDonorName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblOrgan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblOrganType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblMatchCurrentStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMatchStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkMedicalClearance)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRetrievalDate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRetrievalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblRecipientHospitalConfirmations)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkRecipientPreparation)
                                    .addComponent(chkICUBed)))
                            .addComponent(lblTransportOptions)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtTransportOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chkDigitalAgreement)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdateStatus)
                                .addGap(18, 18, 18)
                                .addComponent(btnGenerateChecklist)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatient)
                    .addComponent(lblPatientName)
                    .addComponent(lblDonor)
                    .addComponent(lblDonorName)
                    .addComponent(lblOrgan)
                    .addComponent(lblOrganType)
                    .addComponent(lblMatchCurrentStatus)
                    .addComponent(lblMatchStatus))
                .addGap(30, 30, 30)
                .addComponent(lblDonorHospitalUpdates)
                .addGap(18, 18, 18)
                .addComponent(chkMedicalClearance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRetrievalDate)
                    .addComponent(txtRetrievalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(lblRecipientHospitalConfirmations)
                .addGap(18, 18, 18)
                .addComponent(chkRecipientPreparation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkICUBed)
                .addGap(30, 30, 30)
                .addComponent(lblTransportOptions)
                .addGap(18, 18, 18)
                .addComponent(txtTransportOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(chkDigitalAgreement)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateStatus)
                    .addComponent(btnGenerateChecklist)
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusActionPerformed
        // TODO: Implement logic to validate inputs and update statuses
        if (!txtRetrievalDate.getText().isEmpty()) {
            try {
                organMatch.getDonorRequest().setRetrievalDate(new SimpleDateFormat("yyyy-MM-dd").parse(txtRetrievalDate.getText()));
                organMatch.getDonorRequest().setStatus(RequestStatus.DonorApplicationStatus.RETRIEVAL_SCHEDULED.getValue());
                JOptionPane.showMessageDialog(this, "Retrieval date updated.", "Success", JOptionPane.INFORMATION_MESSAGE);
                lblMatchStatus.setText(organMatch.getStatus());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Invalid date format for retrieval date.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        if (chkMedicalClearance.isSelected() && chkRecipientPreparation.isSelected() && chkICUBed.isSelected() && !txtTransportOptions.getText().isEmpty() && chkDigitalAgreement.isSelected()) {
            organMatch.setStatus("Coordination Complete");
            organMatch.getPatientRequest().setStatus(RequestStatus.PatientRequestStatus.READY_FOR_TRANSPLANT.getValue());
            organMatch.getDonorRequest().setStatus(RequestStatus.DonorApplicationStatus.RETRIEVAL_SCHEDULED.getValue()); // Final status before retrieval
            
            // Route to Logistics for Organ Retrieval & Transport
            LogisticsRequest logisticsRequest = new LogisticsRequest(organMatch);
            logisticsRequest.setSender(organMatch.getPatientRequest().getSender()); // Sender is the doctor who initiated the patient request
            logisticsRequest.setStatus(RequestStatus.OrganLogisticsStatus.RETRIEVAL_SCHEDULED.getValue());
            logisticsRequest.setTransportOption(txtTransportOptions.getText()); // Set transport option from UI
            
            Organization logisticsOrganization = null;
            for (Enterprise e : business.getNetworkList().get(0).getEnterpriseDirectory().getEnterpriseList()) { // Assuming single network for now
                if (e.getEnterpriseType() == Enterprise.EnterpriseType.Logistics) {
                    for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
                        if (org.getType() == Organization.Type.Logistics) {
                            logisticsOrganization = org;
                            break;
                        }
                    }
                }
                if (logisticsOrganization != null) {
                    break;
                }
            }

            if (logisticsOrganization != null) {
                logisticsOrganization.getWorkQueue().addWorkRequest(logisticsRequest);
                organMatch.setStatus(RequestStatus.OrganLogisticsStatus.RETRIEVAL_SCHEDULED.getValue());
                JOptionPane.showMessageDialog(this, "Pre-surgery coordination complete! Request sent to Logistics.", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No Logistics Organization found to process the request.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please ensure all coordination steps are complete before finalizing.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        displayMatchDetails(); // Refresh status display
    }//GEN-LAST:event_btnUpdateStatusActionPerformed

    private void btnGenerateChecklistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateChecklistActionPerformed
        // TODO: Implement logic to generate a surgical checklist (e.g., in a new panel or dialog)
        StringBuilder checklist = new StringBuilder();
        checklist.append("Surgical Checklist for Organ Match (Patient: ").append(organMatch.getPatientRequest().getPatient().getName()).append(", Donor: ").append(organMatch.getDonorRequest().getDonor().getName()).append(")\n\n");
        checklist.append("- Verify Patient ID and medical records.\n");
        checklist.append("- Verify Donor ID and medical records.\n");
        checklist.append("- Confirm required organ: ").append(organMatch.getPatientRequest().getRequiredOrganType()).append("\n");
        checklist.append("- Confirm offered organ: ").append(organMatch.getDonorRequest().getOfferedOrganType()).append("\n");
        checklist.append("- Check blood compatibility.\n");
        checklist.append("- Review tissue markers and antibody profiles.\n");
        checklist.append("- Confirm retrieval date: ").append(txtRetrievalDate.getText()).append("\n");
        checklist.append("- Confirm recipient preparation: ").append(chkRecipientPreparation.isSelected() ? "Yes" : "No").append("\n");
        checklist.append("- Confirm ICU bed reservation: ").append(chkICUBed.isSelected() ? "Yes" : "No").append("\n");
        checklist.append("- Transport options: ").append(txtTransportOptions.getText()).append("\n");
        checklist.append("- Digital Surgical Agreement signed: ").append(chkDigitalAgreement.isSelected() ? "Yes" : "No").append("\n");
        
        JOptionPane.showMessageDialog(this, checklist.toString(), "Surgical Checklist", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnGenerateChecklistActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenerateChecklist;
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JCheckBox chkDigitalAgreement;
    private javax.swing.JCheckBox chkICUBed;
    private javax.swing.JCheckBox chkMedicalClearance;
    private javax.swing.JCheckBox chkRecipientPreparation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDonor;
    private javax.swing.JLabel lblDonorHospitalUpdates;
    private javax.swing.JLabel lblDonorName;
    private javax.swing.JLabel lblMatchCurrentStatus;
    private javax.swing.JLabel lblMatchStatus;
    private javax.swing.JLabel lblOrgan;
    private javax.swing.JLabel lblOrganType;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblRecipientHospitalConfirmations;
    private javax.swing.JLabel lblRetrievalDate;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTransportOptions;
    private javax.swing.JTextField txtRetrievalDate;
    private javax.swing.JTextField txtTransportOptions;
    // End of variables declaration//GEN-END:variables
}
