package userinterface.TransplantCoordinatorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane; // Added import for JOptionPane
import javax.swing.JPanel;

public class TransplantCoordinatorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private Network network;

    /**
     * Creates new form TransplantCoordinatorWorkAreaJPanel
     */
    public TransplantCoordinatorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.network = network;
        
        lblWelcome.setText("Welcome Transplant Coordinator " + account.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        btnManageConnections = new javax.swing.JButton();
        btnReceiveDoctorApproval = new javax.swing.JButton();
        btnScheduleSurgery = new javax.swing.JButton();
        btnRunMatchingAlgorithm = new javax.swing.JButton(); // New button
        btnViewMatchResults = new javax.swing.JButton(); // New button

        setBackground(new java.awt.Color(0, 153, 153));

        lblWelcome.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(204, 255, 204));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome Transplant Coordinator!");

        btnManageConnections.setBackground(new java.awt.Color(0, 102, 102));
        btnManageConnections.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnManageConnections.setForeground(new java.awt.Color(204, 255, 204));
        btnManageConnections.setText("Manage Donor-Recipient Connections");
        btnManageConnections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageConnectionsActionPerformed(evt);
            }
        });

        btnReceiveDoctorApproval.setBackground(new java.awt.Color(0, 102, 102));
        btnReceiveDoctorApproval.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnReceiveDoctorApproval.setForeground(new java.awt.Color(204, 255, 204));
        btnReceiveDoctorApproval.setText("Receive Doctor Approval");
        btnReceiveDoctorApproval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiveDoctorApprovalActionPerformed(evt);
            }
        });

        btnScheduleSurgery.setBackground(new java.awt.Color(0, 102, 102));
        btnScheduleSurgery.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnScheduleSurgery.setForeground(new java.awt.Color(204, 255, 204));
        btnScheduleSurgery.setText("Schedule Surgery");
        btnScheduleSurgery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheduleSurgeryActionPerformed(evt);
            }
        });

        btnRunMatchingAlgorithm.setBackground(new java.awt.Color(0, 102, 102));
        btnRunMatchingAlgorithm.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRunMatchingAlgorithm.setForeground(new java.awt.Color(204, 255, 204));
        btnRunMatchingAlgorithm.setText("Run Matching Algorithm");
        btnRunMatchingAlgorithm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunMatchingAlgorithmActionPerformed(evt);
            }
        });

        btnViewMatchResults.setBackground(new java.awt.Color(0, 102, 102));
        btnViewMatchResults.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnViewMatchResults.setForeground(new java.awt.Color(204, 255, 204));
        btnViewMatchResults.setText("View Match Results");
        btnViewMatchResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMatchResultsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewMatchResults, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRunMatchingAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnScheduleSurgery, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReceiveDoctorApproval, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageConnections, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblWelcome)
                .addGap(80, 80, 80)
                .addComponent(btnRunMatchingAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewMatchResults, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageConnections, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReceiveDoctorApproval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnScheduleSurgery, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageConnectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageConnectionsActionPerformed
        // TODO: Implement logic for managing donor-recipient connections
    }//GEN-LAST:event_btnManageConnectionsActionPerformed

    private void btnReceiveDoctorApprovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiveDoctorApprovalActionPerformed
        // TODO: Implement logic for receiving doctor approval
    }//GEN-LAST:event_btnReceiveDoctorApprovalActionPerformed

    private void btnScheduleSurgeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheduleSurgeryActionPerformed
        // TODO: Implement logic for scheduling surgery
    }//GEN-LAST:event_btnScheduleSurgeryActionPerformed

    private void btnRunMatchingAlgorithmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunMatchingAlgorithmActionPerformed
        business.runOrganMatchingAlgorithm();
        JOptionPane.showMessageDialog(this, "Organ matching algorithm executed successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRunMatchingAlgorithmActionPerformed

    private void btnViewMatchResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMatchResultsActionPerformed
        // TODO: Navigate to ViewMatchResultsJPanel
        // Example:
        // ViewMatchResultsJPanel viewMatchResultsJPanel = new ViewMatchResultsJPanel(userProcessContainer, business);
        // userProcessContainer.add("ViewMatchResultsJPanel", viewMatchResultsJPanel);
        // CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        // layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewMatchResultsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageConnections;
    private javax.swing.JButton btnReceiveDoctorApproval;
    private javax.swing.JButton btnRunMatchingAlgorithm;
    private javax.swing.JButton btnScheduleSurgery;
    private javax.swing.JButton btnViewMatchResults;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
