package userinterface.TransplantCoordinatorRole;

import Business.EcoSystem;
import Business.OrganMatch;
import Business.UserAccount.UserAccount; // Added import
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class ViewMatchResultsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount account; // New field for the current user
    private OrganMatch selectedMatch; // To store the selected organ match

    /**
     * Creates new form ViewMatchResultsJPanel
     */
    public ViewMatchResultsJPanel(JPanel userProcessContainer, EcoSystem business, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.account = account;
        populateMatchResultsTable();
    }

    private void populateMatchResultsTable() {
        DefaultTableModel model = (DefaultTableModel) tblMatchResults.getModel();
        model.setRowCount(0);

        ArrayList<OrganMatch> matchedRequests = business.getMatchedRequests();

        if (matchedRequests.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No organ matches found yet.", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        for (OrganMatch match : matchedRequests) {
            Object[] row = new Object[6];
            row[0] = match.getPatientRequest().getPatient().getName();
            row[1] = match.getPatientRequest().getRequiredOrganType().getValue();
            row[2] = match.getDonorRequest().getDonor().getName();
            row[3] = match.getDonorRequest().getDonor().getBloodType().getValue();
            row[4] = String.format("%.2f", match.getMatchScore()); // Format score to 2 decimal places
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMatchResults = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMatchResults = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnSelectMatch = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        lblMatchResults.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblMatchResults.setForeground(new java.awt.Color(204, 255, 204));
        lblMatchResults.setText("Organ Match Results");

        tblMatchResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Patient Blood Type", "Required Organ", "Donor Name", "Donor Blood Type", "Match Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMatchResults);

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(204, 255, 204));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSelectMatch.setBackground(new java.awt.Color(0, 102, 102));
        btnSelectMatch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSelectMatch.setForeground(new java.awt.Color(204, 255, 204));
        btnSelectMatch.setText("Select Match");
        btnSelectMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectMatchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(lblMatchResults)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSelectMatch)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblMatchResults)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSelectMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnBack)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSelectMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectMatchActionPerformed
        int selectedRow = tblMatchResults.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a match to proceed.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // TODO: Implement logic to handle the selected match, e.g.,
        //  - Mark the requests as 'accepted' or 'in-progress'
        //  - Navigate to a panel for further coordination
        JOptionPane.showMessageDialog(this, "Match selected successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        EcoSystem.sendNotification(account, "Match for Patient " + selectedMatch.getPatientRequest().getPatient().getName() + " and Donor " + selectedMatch.getDonorRequest().getDonor().getName() + " has been selected.");
        // TODO: Implement logic to send a notification to the relevant Case Manager
    }//GEN-LAST:event_btnSelectMatchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSelectMatch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMatchResults;
    private javax.swing.JTable tblMatchResults;
    // End of variables declaration//GEN-END:variables
}