/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CaseManagerRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Magic.Design.*;
import Business.OrganMatch; // Import OrganMatch
import Business.Organization.LogisticsOrganization;
import Business.Organization.Organization;
import Business.People.Patient;
import Business.Requests.PatientRequest;
import Business.Requests.LogisticsRequest; // Added import
import Business.Statuses.RequestStatus; // Added import for RequestStatus
import Business.UserAccount.UserAccount;
import Business.WorkQueue.System_Coordinator_Test_WorkRequest;
import Business.WorkQueue.WorkRequest;
import Magic.Design.MyJButton;
import Magic.Design.MyTableFormat;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Ing-Ruei
 */
public class PrepareOrderDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerReceiverRequestJPanel
     */
    private EcoSystem system;
    private UserAccount userAccount;
    private Network network;
    private OrganMatch selectedMatch; // To store the selected organ match
    private JPanel userProcessContainer;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public PrepareOrderDetailsJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, EcoSystem system, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = userAccount;
        this.network = network;
        tblMatchedOrders.getTableHeader().setDefaultRenderer(new MyTableFormat()); // Assuming MyTableFormat is available
        populateMatchedOrdersTable();
    }
  

    private void populateMatchedOrdersTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblMatchedOrders.getModel();
        
        dtm.setRowCount(0);
        
        for(OrganMatch match : system.getMatchedRequests()){            
            Object row[] = new Object[8];
            row[0]= match; // Display Match ID (or toString of OrganMatch)
            row[1]= match.getPatientRequest().getPatient().getName();
            row[2]= match.getPatientRequest().getRequiredOrganType().getValue();
            row[3]= match.getPatientRequest().getPatient().getBloodType().getValue();
            row[4]= match.getDonorRequest().getDonor().getName();
            row[5]= match.getDonorRequest().getOfferedOrganType().getValue();
            row[6]= match.getDonorRequest().getDonor().getBloodType().getValue();
            row[7]= String.format("%.2f", match.getMatchScore());
              
            dtm.addRow(row);
        }        
    }
    
    private void populateMatchDetails(OrganMatch match) {
        txtPatientName.setText(match.getPatientRequest().getPatient().getName());
        txtRequiredOrgan.setText(match.getPatientRequest().getRequiredOrganType().getValue());
        txtPatientBloodType.setText(match.getPatientRequest().getPatient().getBloodType().getValue());
        txtMatchStatus.setText(match.getStatus());

        txtDonorName.setText(match.getDonorRequest().getDonor().getName());
        txtOfferedOrgan.setText(match.getDonorRequest().getOfferedOrganType().getValue());
        txtDonorBloodType.setText(match.getDonorRequest().getDonor().getBloodType().getValue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMatchedOrders = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        lblPatientDetails = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        lblRequiredOrgan = new javax.swing.JLabel();
        txtRequiredOrgan = new javax.swing.JTextField();
        lblPatientBloodType = new javax.swing.JLabel();
        txtPatientBloodType = new javax.swing.JTextField();
        lblDonorDetails = new javax.swing.JLabel();
        lblDonorName = new javax.swing.JLabel();
        txtDonorName = new javax.swing.JTextField();
        lblOfferedOrgan = new javax.swing.JLabel();
        txtOfferedOrgan = new javax.swing.JTextField();
        lblDonorBloodType = new javax.swing.JLabel();
        txtDonorBloodType = new javax.swing.JTextField();
        btnProcessOrder = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblMatchStatus = new javax.swing.JLabel();
        txtMatchStatus = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(204, 255, 204));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1150, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(926, 70));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Prepare Matched Order");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 973, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(558, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, -1));

        tblMatchedOrders.setBackground(new java.awt.Color(0, 102, 102));
        tblMatchedOrders.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        tblMatchedOrders.setForeground(new java.awt.Color(204, 255, 204));
        tblMatchedOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Match ID", "Patient Name", "Required Organ", "Patient Blood Type", "Donor Name", "Offered Organ", "Donor Blood Type", "Match Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMatchedOrders.setFocusable(false);
        tblMatchedOrders.setGridColor(new java.awt.Color(0, 0, 0));
        tblMatchedOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblMatchedOrdersMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblMatchedOrders);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 980, 130));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 860, -1));

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("Selected Match Details");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, -1, -1));

        lblPatientDetails.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPatientDetails.setForeground(new java.awt.Color(204, 255, 204));
        lblPatientDetails.setText("Patient Details:");
        add(lblPatientDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        lblPatientName.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblPatientName.setForeground(new java.awt.Color(204, 255, 204));
        lblPatientName.setText("Name:");
        add(lblPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        txtPatientName.setEditable(false);
        txtPatientName.setBackground(new java.awt.Color(0, 153, 153));
        txtPatientName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtPatientName.setForeground(new java.awt.Color(204, 255, 204));
        add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 200, -1));

        lblRequiredOrgan.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblRequiredOrgan.setForeground(new java.awt.Color(204, 255, 204));
        lblRequiredOrgan.setText("Required Organ:");
        add(lblRequiredOrgan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        txtRequiredOrgan.setEditable(false);
        txtRequiredOrgan.setBackground(new java.awt.Color(0, 153, 153));
        txtRequiredOrgan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtRequiredOrgan.setForeground(new java.awt.Color(204, 255, 204));
        add(txtRequiredOrgan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 200, -1));

        lblPatientBloodType.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblPatientBloodType.setForeground(new java.awt.Color(204, 255, 204));
        lblPatientBloodType.setText("Blood Type:");
        add(lblPatientBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        txtPatientBloodType.setEditable(false);
        txtPatientBloodType.setBackground(new java.awt.Color(0, 153, 153));
        txtPatientBloodType.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtPatientBloodType.setForeground(new java.awt.Color(204, 255, 204));
        add(txtPatientBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 200, -1));

        lblDonorDetails.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDonorDetails.setForeground(new java.awt.Color(204, 255, 204));
        lblDonorDetails.setText("Donor Details:");
        add(lblDonorDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, -1));

        lblDonorName.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblDonorName.setForeground(new java.awt.Color(204, 255, 204));
        lblDonorName.setText("Name:");
        add(lblDonorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        txtDonorName.setEditable(false);
        txtDonorName.setBackground(new java.awt.Color(0, 153, 153));
        txtDonorName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtDonorName.setForeground(new java.awt.Color(204, 255, 204));
        add(txtDonorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 200, -1));

        lblOfferedOrgan.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblOfferedOrgan.setForeground(new java.awt.Color(204, 255, 204));
        lblOfferedOrgan.setText("Offered Organ:");
        add(lblOfferedOrgan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, -1));

        txtOfferedOrgan.setEditable(false);
        txtOfferedOrgan.setBackground(new java.awt.Color(0, 153, 153));
        txtOfferedOrgan.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtOfferedOrgan.setForeground(new java.awt.Color(204, 255, 204));
        add(txtOfferedOrgan, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 200, -1));

        lblDonorBloodType.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblDonorBloodType.setForeground(new java.awt.Color(204, 255, 204));
        lblDonorBloodType.setText("Blood Type:");
        add(lblDonorBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, -1, -1));

        txtDonorBloodType.setEditable(false);
        txtDonorBloodType.setBackground(new java.awt.Color(0, 153, 153));
        txtDonorBloodType.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtDonorBloodType.setForeground(new java.awt.Color(204, 255, 204));
        add(txtDonorBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 200, -1));

        btnProcessOrder.setBackground(new java.awt.Color(0, 102, 102));
        btnProcessOrder.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnProcessOrder.setForeground(new java.awt.Color(204, 255, 204));
        btnProcessOrder.setText("Process Order");
        btnProcessOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessOrderActionPerformed(evt);
            }
        });
        add(btnProcessOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, 150, 40));

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(204, 255, 204));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, -1, -1));

        lblMatchStatus.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblMatchStatus.setForeground(new java.awt.Color(204, 255, 204));
        lblMatchStatus.setText("Match Status:");
        add(lblMatchStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        txtMatchStatus.setEditable(false);
        txtMatchStatus.setBackground(new java.awt.Color(0, 153, 153));
        txtMatchStatus.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtMatchStatus.setForeground(new java.awt.Color(204, 255, 204));
        add(txtMatchStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tblMatchedOrdersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMatchedOrdersMousePressed
        int selectedRow = tblMatchedOrders.getSelectedRow();
        if(selectedRow < 0){
            return;
        }
        
        selectedMatch = (OrganMatch) tblMatchedOrders.getValueAt(selectedRow, 0);
        populateMatchDetails(selectedMatch);
        btnProcessOrder.setEnabled(true);
    }//GEN-LAST:event_tblMatchedOrdersMousePressed

    private void btnProcessOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessOrderActionPerformed
        if (selectedMatch == null) {
            JOptionPane.showMessageDialog(this, "Please select an organ match to process.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Update the status of the selected match
        selectedMatch.setStatus("Processed by Case Manager");
        
        // Create and send a LogisticsRequest
        LogisticsRequest logisticsRequest = new LogisticsRequest(selectedMatch);
        logisticsRequest.setOrganMatch(selectedMatch);
        logisticsRequest.setSender(userAccount);
        logisticsRequest.setStatus(RequestStatus.OrganLogisticsStatus.READY_FOR_TRANSPORT.getValue());
        logisticsRequest.setRequestDate(new Date());

        // Find the LogisticsOrganization in the current network and add the request
        Organization org = null;
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            for (Organization organization : e.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof LogisticsOrganization) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                break;
            }
        }

        if (org != null) {
            org.getWorkQueue().addWorkRequest(logisticsRequest);
            userAccount.getWorkQueue().add(logisticsRequest); // Add to sender's work queue as well
            selectedMatch.setStatus(RequestStatus.OrganLogisticsStatus.READY_FOR_TRANSPORT.getValue()); // Update OrganMatch status
            JOptionPane.showMessageDialog(this, "Organ match processed and Logistics Request sent successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            // Send notification to a Logistics Officer
            UserAccount logisticsOfficerAccount = null;
            for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
                if (ua.getRole() instanceof Business.Role.LogisticsOfficerRole) {
                    logisticsOfficerAccount = ua;
                    break;
                }
            }
            if (logisticsOfficerAccount != null) {
                EcoSystem.sendNotification(logisticsOfficerAccount, "New Organ Logistics Request for Match ID: " + selectedMatch.getMatchId() + " from Case Manager " + userAccount.getUsername());
            } else {
                System.err.println("No Logistics Officer found in the Logistics Organization to send notification.");
            }

        } else {
            JOptionPane.showMessageDialog(this, "No Logistics Organization found to send the request to.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        dB4OUtil.storeSystem(system);
        populateMatchedOrdersTable(); // Refresh the table
        // Clear details or disable buttons after processing
        txtPatientName.setText("");
        txtRequiredOrgan.setText("");
        txtPatientBloodType.setText("");
        txtMatchStatus.setText("");
        txtDonorName.setText("");
        txtOfferedOrgan.setText("");
        txtDonorBloodType.setText("");
        btnProcessOrder.setEnabled(false);
    }//GEN-LAST:event_btnProcessOrderActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnProcessOrder;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblDonorBloodType;
    private javax.swing.JLabel lblDonorDetails;
    private javax.swing.JLabel lblDonorName;
    private javax.swing.JLabel lblMatchStatus;
    private javax.swing.JLabel lblOfferedOrgan;
    private javax.swing.JLabel lblPatientBloodType;
    private javax.swing.JLabel lblPatientDetails;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblRequiredOrgan;
    private javax.swing.JTable tblMatchedOrders;
    private javax.swing.JTextField txtDonorBloodType;
    private javax.swing.JTextField txtDonorName;
    private javax.swing.JTextField txtMatchStatus;
    private javax.swing.JTextField txtOfferedOrgan;
    private javax.swing.JTextField txtPatientBloodType;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtRequiredOrgan;
    // End of variables declaration//GEN-END:variables
}