package userinterface.RecipientRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.CustomerRole.PickCustomerActionJPanel;

/**
     * Creates new form RecipientWorkAreaJPanel
     */

public class RecipientWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private Network network;

    /**
     * Creates new form RecipientWorkAreaJPanel
     */
    public RecipientWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.network = network;
        
        lblWelcome.setText("Welcome Recipient " + account.getEmployee().getName());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        btnPaitientsRegistration = new javax.swing.JButton();
        btnViewRequestStatus = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        lblWelcome.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(204, 255, 204));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome Recipient!");

        btnPaitientsRegistration.setBackground(new java.awt.Color(0, 102, 102));
        btnPaitientsRegistration.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPaitientsRegistration.setForeground(new java.awt.Color(204, 255, 204));
        btnPaitientsRegistration.setText("Paitient Registration");
        btnPaitientsRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaitientsRegistrationActionPerformed(evt);
            }
        });

        btnViewRequestStatus.setBackground(new java.awt.Color(0, 102, 102));
        btnViewRequestStatus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnViewRequestStatus.setForeground(new java.awt.Color(204, 255, 204));
        btnViewRequestStatus.setText("View Request Status");
        btnViewRequestStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequestStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPaitientsRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewRequestStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblWelcome)
                .addGap(80, 80, 80)
                .addComponent(btnPaitientsRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewRequestStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPaitientsRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequestStatusActionPerformed
        // TODO: Implement logic for viewing request status
        PatientsRegistrationJPanel PatientsRegistrationJPanel = new PatientsRegistrationJPanel(
        userProcessContainer, 
        account, 
        organization, 
        enterprise, 
        business, 
        network
    );
        // 使用 CardLayout 切换到新页面
        userProcessContainer.add("PatientsRegistrationJPanel", PatientsRegistrationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewRequestStatusActionPerformed

    private void btnViewRequestStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEstimatedWaitTimeActionPerformed
        // TODO: Implement logic for viewing estimated wait time
        ViewRequestStatusJPanel ViewRequestStatusJPanel = new ViewRequestStatusJPanel(
        userProcessContainer, 
        account, 
        organization, 
        enterprise, 
        business, 
        network
    );
        // 使用 CardLayout 切换到新页面
        userProcessContainer.add("ViewRequestStatusJPanel", ViewRequestStatusJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewEstimatedWaitTimeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPaitientsRegistration;
    private javax.swing.JButton btnViewRequestStatus;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
