package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private Network network;

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.network = network;
        
        lblWelcome.setText("Welcome Dr. " + account.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        btnAssignToLabTech = new javax.swing.JButton();
        btnReviewTestReports = new javax.swing.JButton();
        btnSubmitSurgeryRequest = new javax.swing.JButton();
        btnRegisterNewPatient = new javax.swing.JButton(); // Added button
        btnManageSurgeries = new javax.swing.JButton(); // New button

        setBackground(new java.awt.Color(0, 153, 153));

        lblWelcome.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(204, 255, 204));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome Doctor!");

        btnAssignToLabTech.setBackground(new java.awt.Color(0, 102, 102));
        btnAssignToLabTech.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAssignToLabTech.setForeground(new java.awt.Color(204, 255, 204));
        btnAssignToLabTech.setText("Assign Case to Lab Technician");
        btnAssignToLabTech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToLabTechActionPerformed(evt);
            }
        });

        btnReviewTestReports.setBackground(new java.awt.Color(0, 102, 102));
        btnReviewTestReports.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnReviewTestReports.setForeground(new java.awt.Color(204, 255, 204));
        btnReviewTestReports.setText("Review Test Reports");
        btnReviewTestReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewTestReportsActionPerformed(evt);
            }
        });

        btnSubmitSurgeryRequest.setBackground(new java.awt.Color(0, 102, 102));
        btnSubmitSurgeryRequest.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSubmitSurgeryRequest.setForeground(new java.awt.Color(204, 255, 204));
        btnSubmitSurgeryRequest.setText("Submit Surgery Request");
        btnSubmitSurgeryRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitSurgeryRequestActionPerformed(evt);
            }
        });

        btnRegisterNewPatient.setBackground(new java.awt.Color(0, 102, 102));
        btnRegisterNewPatient.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegisterNewPatient.setForeground(new java.awt.Color(204, 255, 204));
        btnRegisterNewPatient.setText("Register New Patient");
        btnRegisterNewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterNewPatientActionPerformed(evt);
            }
        });

        btnManageSurgeries.setBackground(new java.awt.Color(0, 102, 102));
        btnManageSurgeries.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnManageSurgeries.setForeground(new java.awt.Color(204, 255, 204));
        btnManageSurgeries.setText("Manage Surgeries");
        btnManageSurgeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSurgeriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageSurgeries, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterNewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmitSurgeryRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReviewTestReports, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssignToLabTech, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblWelcome)
                .addGap(80, 80, 80)
                .addComponent(btnRegisterNewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAssignToLabTech, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReviewTestReports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSubmitSurgeryRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageSurgeries, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignToLabTechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToLabTechActionPerformed
        // TODO: Implement logic for assigning cases to Lab Technicians
        // Example: userProcessContainer.add("AssignLabTechJPanel", new AssignLabTechJPanel(...));
        // CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        // layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAssignToLabTechActionPerformed

    private void btnReviewTestReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewTestReportsActionPerformed
        // TODO: Implement logic for reviewing test reports
    }//GEN-LAST:event_btnReviewTestReportsActionPerformed

    private void btnSubmitSurgeryRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitSurgeryRequestActionPerformed
        // TODO: Implement logic for submitting surgery requests
    }//GEN-LAST:event_btnSubmitSurgeryRequestActionPerformed

    private void btnRegisterNewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterNewPatientActionPerformed
        RegisterPatientJPanel registerPatientJPanel = new RegisterPatientJPanel(userProcessContainer, account, organization, enterprise, business, network);
        userProcessContainer.add("RegisterPatientJPanel", registerPatientJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRegisterNewPatientActionPerformed

    private void btnManageSurgeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSurgeriesActionPerformed
        ManageSurgeriesJPanel manageSurgeriesJPanel = new ManageSurgeriesJPanel(userProcessContainer, account, organization, enterprise, business, network);
        userProcessContainer.add("ManageSurgeriesJPanel", manageSurgeriesJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageSurgeriesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToLabTech;
    private javax.swing.JButton btnManageSurgeries;
    private javax.swing.JButton btnRegisterNewPatient;
    private javax.swing.JButton btnReviewTestReports;
    private javax.swing.JButton btnSubmitSurgeryRequest;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}