package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Requests.SurgeryRequest;
import Business.Statuses.RequestStatus;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class ManageSurgeriesJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private Network network;

    /**
     * Creates new form ManageSurgeriesJPanel
     */
    public ManageSurgeriesJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.network = network;
        
        populateRequestTable();
    }
    
    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) tblSurgeryRequests.getModel();
        model.setRowCount(0);
        
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof SurgeryRequest) {
                SurgeryRequest surgeryRequest = (SurgeryRequest) request;
                Object[] row = new Object[7];
                row[0] = surgeryRequest; // The SurgeryRequest object itself
                row[1] = surgeryRequest.getOrganMatch().getPatientRequest().getPatient().getName();
                row[2] = surgeryRequest.getOrganMatch().getDonorRequest().getDonor().getName();
                row[3] = surgeryRequest.getOrganMatch().getPatientRequest().getRequiredOrganType();
                row[4] = surgeryRequest.getSurgeryStatus();
                row[5] = surgeryRequest.getReceiver() == null ? "Not Assigned" : surgeryRequest.getReceiver().getEmployee().getName();
                row[6] = surgeryRequest.getRequestDate();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSurgeryRequests = new javax.swing.JTable();
        btnAssignToMe = new javax.swing.JButton();
        btnUpdateStatus = new javax.swing.JButton();
        btnRecordOutcome = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblSurgeryDate = new javax.swing.JLabel();
        txtSurgeryDate = new javax.swing.JTextField();
        lblInitialOutcome = new javax.swing.JLabel();
        txtInitialOutcome = new javax.swing.JTextField();
        btnRecordFollowUp = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 255, 204));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Surgeries");

        tblSurgeryRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Patient", "Donor", "Organ", "Status", "Assigned To", "Request Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSurgeryRequests);

        btnAssignToMe.setBackground(new java.awt.Color(0, 102, 102));
        btnAssignToMe.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAssignToMe.setForeground(new java.awt.Color(204, 255, 204));
        btnAssignToMe.setText("Assign to Me");
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });

        btnUpdateStatus.setBackground(new java.awt.Color(0, 102, 102));
        btnUpdateStatus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnUpdateStatus.setForeground(new java.awt.Color(204, 255, 204));
        btnUpdateStatus.setText("Update Status");
        btnUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStatusActionPerformed(evt);
            }
        });

        btnRecordOutcome.setBackground(new java.awt.Color(0, 102, 102));
        btnRecordOutcome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRecordOutcome.setForeground(new java.awt.Color(204, 255, 204));
        btnRecordOutcome.setText("Record Initial Outcome");
        btnRecordOutcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordOutcomeActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(204, 255, 204));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblSurgeryDate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSurgeryDate.setForeground(new java.awt.Color(204, 255, 204));
        lblSurgeryDate.setText("Surgery Date (YYYY-MM-DD):");

        lblInitialOutcome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblInitialOutcome.setForeground(new java.awt.Color(204, 255, 204));
        lblInitialOutcome.setText("Initial Outcome:");

        btnRecordFollowUp.setBackground(new java.awt.Color(0, 102, 102));
        btnRecordFollowUp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRecordFollowUp.setForeground(new java.awt.Color(204, 255, 204));
        btnRecordFollowUp.setText("Record Follow-up");
        btnRecordFollowUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordFollowUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(18, 18, 18)
                        .addComponent(btnAssignToMe)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateStatus)
                        .addGap(18, 18, 18)
                        .addComponent(btnRecordOutcome)
                        .addGap(18, 18, 18)
                        .addComponent(btnRecordFollowUp))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblSurgeryDate)
                            .addGap(18, 18, 18)
                            .addComponent(txtSurgeryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblInitialOutcome)
                            .addGap(18, 18, 18)
                            .addComponent(txtInitialOutcome))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssignToMe)
                    .addComponent(btnUpdateStatus)
                    .addComponent(btnRecordOutcome)
                    .addComponent(btnBack)
                    .addComponent(btnRecordFollowUp))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurgeryDate)
                    .addComponent(txtSurgeryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInitialOutcome)
                    .addComponent(txtInitialOutcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed
        int selectedRow = tblSurgeryRequests.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request to assign.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        SurgeryRequest request = (SurgeryRequest) tblSurgeryRequests.getValueAt(selectedRow, 0);
        if (!request.getSurgeryStatus().equals(RequestStatus.SurgeryStatus.SCHEDULED.getValue())) {
            JOptionPane.showMessageDialog(this, "Request is not in 'Scheduled' status and cannot be assigned.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        request.setReceiver(account);
        request.setSurgeryStatus(RequestStatus.SurgeryStatus.PRE_OP_PREPARATION.getValue()); // Or 'Commenced'
        JOptionPane.showMessageDialog(this, "Request assigned to you. Status updated to 'Pre-Op Preparation'.", "Success", JOptionPane.INFORMATION_MESSAGE);
        populateRequestTable();
    }//GEN-LAST:event_btnAssignToMeActionPerformed

    private void btnUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusActionPerformed
        int selectedRow = tblSurgeryRequests.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request to update.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        SurgeryRequest request = (SurgeryRequest) tblSurgeryRequests.getValueAt(selectedRow, 0);
        if (request.getReceiver() == null || !request.getReceiver().equals(account)) {
            JOptionPane.showMessageDialog(this, "Request is not assigned to you.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String newStatus = JOptionPane.showInputDialog(this, "Enter new status (e.g., Commenced, Completed, Complications Noted):");
        if (newStatus != null && !newStatus.trim().isEmpty()) {
            request.setSurgeryStatus(newStatus.trim());
            if (newStatus.trim().equalsIgnoreCase(RequestStatus.SurgeryStatus.COMPLETED.getValue())) {
                request.getOrganMatch().setStatus(RequestStatus.SurgeryStatus.COMPLETED.getValue()); // Update OrganMatch status
                request.setResolveDate(new Date());
            }
            if (!txtSurgeryDate.getText().isEmpty()) {
                try {
                    request.setSurgeryDate(new SimpleDateFormat("yyyy-MM-dd").parse(txtSurgeryDate.getText()));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Invalid date format for surgery date.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            
            JOptionPane.showMessageDialog(this, "Surgery status updated to " + newStatus.trim() + ".", "Success", JOptionPane.INFORMATION_MESSAGE);
            populateRequestTable();
        } else {
            JOptionPane.showMessageDialog(this, "New status cannot be empty.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateStatusActionPerformed

    private void btnRecordOutcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordOutcomeActionPerformed
        int selectedRow = tblSurgeryRequests.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request to record outcome for.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        SurgeryRequest request = (SurgeryRequest) tblSurgeryRequests.getValueAt(selectedRow, 0);
        if (request.getReceiver() == null || !request.getReceiver().equals(account)) {
            JOptionPane.showMessageDialog(this, "Request is not assigned to you.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String outcome = txtInitialOutcome.getText();
        if (outcome != null && !outcome.trim().isEmpty()) {
            request.setInitialOutcome(outcome.trim());
            JOptionPane.showMessageDialog(this, "Initial outcome recorded.", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Outcome cannot be empty.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRecordOutcomeActionPerformed

    private void btnRecordFollowUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordFollowUpActionPerformed
        int selectedRow = tblSurgeryRequests.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request to record follow-up for.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        SurgeryRequest request = (SurgeryRequest) tblSurgeryRequests.getValueAt(selectedRow, 0);
        if (request.getReceiver() == null || !request.getReceiver().equals(account)) {
            JOptionPane.showMessageDialog(this, "Request is not assigned to you.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Example: navigate to a dedicated follow-up panel
        // For simplicity, directly updating follow-up reports here
        String followUp = JOptionPane.showInputDialog(this, "Enter follow-up report:");
        if (followUp != null && !followUp.trim().isEmpty()) {
            request.setFollowUpReport(followUp.trim());
            // This is a simplified way to handle multiple follow-ups, in a real app, you'd likely have a list of follow-up objects
            request.setSurgeryStatus(RequestStatus.SurgeryStatus.POST_OP_FOLLOWUP.getValue());
            JOptionPane.showMessageDialog(this, "Follow-up report recorded.", "Success", JOptionPane.INFORMATION_MESSAGE);
            populateRequestTable();
        } else {
            JOptionPane.showMessageDialog(this, "Follow-up report cannot be empty.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRecordFollowUpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRecordFollowUp;
    private javax.swing.JButton btnRecordOutcome;
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInitialOutcome;
    private javax.swing.JLabel lblSurgeryDate;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblSurgeryRequests;
    private javax.swing.JTextField txtInitialOutcome;
    private javax.swing.JTextField txtSurgeryDate;
    // End of variables declaration//GEN-END:variables
}
