package userinterface.DoctorRole;

import Business.BloodTypes.PersonBloodTypes;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.People.Patient;
import Business.Requests.PatientRequest;
import Business.Statuses.RequestStatus;
import Business.OrganTypes.OrganType;
import Business.Requests.MedicalUrgencyLevel; // Added import
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.DoctorRole.DoctorWorkAreaJPanel;

public class RegisterPatientJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private Network network;

    /**
     * Creates new form RegisterPatientJPanel
     */
    public RegisterPatientJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.network = network;
        
        populateComboBoxes();
        setupUrgencyLevelRadioButtons();
    }

    private void populateComboBoxes() {
        cbRequiredOrganType.setModel(new DefaultComboBoxModel(OrganType.values()));
        cbBloodType.setModel(new DefaultComboBoxModel(PersonBloodTypes.BloodType.values()));
    }
    
    private void setupUrgencyLevelRadioButtons() {
        ButtonGroup group = new ButtonGroup();
        group.add(rbCritical);
        group.add(rbHigh);
        group.add(rbMedium);
        group.add(rbStandard);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        lblContact = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lblStreetAddress = new javax.swing.JLabel();
        txtStreetAddress = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        lblZipCode = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblBloodType = new javax.swing.JLabel();
        cbBloodType = new javax.swing.JComboBox();
        lblRequiredOrganType = new javax.swing.JLabel();
        cbRequiredOrganType = new javax.swing.JComboBox();
        lblTissueMarkers = new javax.swing.JLabel();
        txtTissueMarkers = new javax.swing.JTextField();
        lblAntibodyProfile = new javax.swing.JLabel();
        txtAntibodyProfile = new javax.swing.JTextField();
        lblUrgencyLevel = new javax.swing.JLabel();
        rbCritical = new javax.swing.JRadioButton();
        rbHigh = new javax.swing.JRadioButton();
        rbMedium = new javax.swing.JRadioButton();
        rbStandard = new javax.swing.JRadioButton();
        lblContraindications = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaContraindications = new javax.swing.JTextArea();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 255, 204));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Patient Registration Form");

        lblName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(204, 255, 204));
        lblName.setText("Name:");

        lblDOB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(204, 255, 204));
        lblDOB.setText("Date of Birth (YYYY-MM-DD):");

        lblContact.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblContact.setForeground(new java.awt.Color(204, 255, 204));
        lblContact.setText("Contact:");

        lblGender.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblGender.setForeground(new java.awt.Color(204, 255, 204));
        lblGender.setText("Gender:");

        lblStreetAddress.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblStreetAddress.setForeground(new java.awt.Color(204, 255, 204));
        lblStreetAddress.setText("Street Address:");

        lblCity.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCity.setForeground(new java.awt.Color(204, 255, 204));
        lblCity.setText("City:");

        lblState.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblState.setForeground(new java.awt.Color(204, 255, 204));
        lblState.setText("State:");

        lblZipCode.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblZipCode.setForeground(new java.awt.Color(204, 255, 204));
        lblZipCode.setText("Zip Code:");

        lblEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(204, 255, 204));
        lblEmail.setText("Email:");

        lblBloodType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblBloodType.setForeground(new java.awt.Color(204, 255, 204));
        lblBloodType.setText("Blood Type:");

        cbBloodType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblRequiredOrganType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblRequiredOrganType.setForeground(new java.awt.Color(204, 255, 204));
        lblRequiredOrganType.setText("Required Organ Type:");

        cbRequiredOrganType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTissueMarkers.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTissueMarkers.setForeground(new java.awt.Color(204, 255, 204));
        lblTissueMarkers.setText("Tissue Markers:");

        lblAntibodyProfile.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAntibodyProfile.setForeground(new java.awt.Color(204, 255, 204));
        lblAntibodyProfile.setText("Antibody Profile:");

        lblUrgencyLevel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUrgencyLevel.setForeground(new java.awt.Color(204, 255, 204));
        lblUrgencyLevel.setText("Medical Urgency Level:");

        rbCritical.setBackground(new java.awt.Color(0, 153, 153));
        rbCritical.setForeground(new java.awt.Color(204, 255, 204));
        rbCritical.setText("Critical");

        rbHigh.setBackground(new java.awt.Color(0, 153, 153));
        rbHigh.setForeground(new java.awt.Color(204, 255, 204));
        rbHigh.setText("High");

        rbMedium.setBackground(new java.awt.Color(0, 153, 153));
        rbMedium.setForeground(new java.awt.Color(204, 255, 204));
        rbMedium.setText("Medium");

        rbStandard.setBackground(new java.awt.Color(0, 153, 153));
        rbStandard.setForeground(new java.awt.Color(204, 255, 204));
        rbStandard.setText("Standard");

        lblContraindications.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblContraindications.setForeground(new java.awt.Color(204, 255, 204));
        lblContraindications.setText("Contraindications / Special Requirements:");

        txtAreaContraindications.setColumns(20);
        txtAreaContraindications.setRows(5);
        jScrollPane1.setViewportView(txtAreaContraindications);

        btnSubmit.setBackground(new java.awt.Color(0, 102, 102));
        btnSubmit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(204, 255, 204));
        btnSubmit.setText("Submit Registration");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(204, 255, 204));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(158, 158, 158)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContraindications)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUrgencyLevel)
                                    .addComponent(lblAntibodyProfile)
                                    .addComponent(lblTissueMarkers)
                                    .addComponent(lblRequiredOrganType)
                                    .addComponent(lblBloodType)
                                    .addComponent(lblEmail)
                                    .addComponent(lblZipCode)
                                    .addComponent(lblState)
                                    .addComponent(lblCity)
                                    .addComponent(lblStreetAddress)
                                    .addComponent(lblGender)
                                    .addComponent(lblContact)
                                    .addComponent(lblDOB)
                                    .addComponent(lblName))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName)
                                    .addComponent(txtDOB)
                                    .addComponent(txtContact)
                                    .addComponent(txtGender)
                                    .addComponent(txtStreetAddress)
                                    .addComponent(txtCity)
                                    .addComponent(txtState)
                                    .addComponent(txtZipCode)
                                    .addComponent(txtEmail)
                                    .addComponent(cbBloodType, 0, 200, Short.MAX_VALUE)
                                    .addComponent(cbRequiredOrganType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTissueMarkers)
                                    .addComponent(txtAntibodyProfile)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbCritical)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbHigh)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbMedium)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbStandard)))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOB)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContact)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreetAddress)
                    .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipCode)
                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloodType)
                    .addComponent(cbBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRequiredOrganType)
                    .addComponent(cbRequiredOrganType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTissueMarkers)
                    .addComponent(txtTissueMarkers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAntibodyProfile)
                    .addComponent(txtAntibodyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUrgencyLevel)
                    .addComponent(rbCritical)
                    .addComponent(rbHigh)
                    .addComponent(rbMedium)
                    .addComponent(rbStandard))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContraindications)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        try {
            // Create a new Patient object and populate its fields from the form
            Patient patient = new Patient();
            patient.setName(txtName.getText());
            patient.setDob(new SimpleDateFormat("yyyy-MM-dd").parse(txtDOB.getText()));
            patient.setContact(Long.parseLong(txtContact.getText()));
            patient.setGender(txtGender.getText());
            patient.setStreetAddress(txtStreetAddress.getText());
            patient.setCity(txtCity.getText());
            patient.setState(txtState.getText());
            patient.setZipCode(Integer.parseInt(txtZipCode.getText()));
            patient.setEmailID(txtEmail.getText());
            patient.setBloodType((PersonBloodTypes.BloodType) cbBloodType.getSelectedItem());
            patient.setTissueMarkers(txtTissueMarkers.getText());
            patient.setAntibodyProfile(txtAntibodyProfile.getText());
            
            // Generate patient ID
            patient.setReceiverID("PAT-" + System.currentTimeMillis());

            // Add the patient to the EcoSystem's patient directory
            business.getPatientDirectory().addPatient(patient);
            
            // Create a new PatientRequest
            PatientRequest patientRequest = new PatientRequest();
            patientRequest.setRequiredOrganType((OrganType) cbRequiredOrganType.getSelectedItem());
            
            String urgencyString = "";
            if(rbCritical.isSelected()) urgencyString = "CRITICAL";
            else if(rbHigh.isSelected()) urgencyString = "HIGH";
            else if(rbMedium.isSelected()) urgencyString = "MEDIUM";
            else if(rbStandard.isSelected()) urgencyString = "STANDARD";
            
            patientRequest.setMedicalUrgencyLevel(MedicalUrgencyLevel.valueOf(urgencyString));
            
            patientRequest.setContraindications(txtAreaContraindications.getText());
            patientRequest.setSender(account); // Doctor is sending the request
            patientRequest.setPatient(patient); // Link the patient object to the request
            patientRequest.setStatus(RequestStatus.PatientRequestStatus.PENDING_VERIFICATION.getValue());

            // Route the PatientRequest to an appropriate HospitalOrganization for verification
            Organization hospitalOrganization = null;
            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (e.getEnterpriseType() == Enterprise.EnterpriseType.Hospital) {
                    for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
                        if (org.getType() == Organization.Type.Hospital) {
                            hospitalOrganization = org;
                            break;
                        }
                    }
                }
                if (hospitalOrganization != null) {
                    break;
                }
            }

            if (hospitalOrganization != null) {
                hospitalOrganization.getWorkQueue().addWorkRequest(patientRequest);
                JOptionPane.showMessageDialog(this, "Patient registration submitted successfully and sent for verification!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No Hospital Organization found to process the request.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            userProcessContainer.removeAll();
            userProcessContainer.add("DoctorWorkAreaJPanel", new DoctorWorkAreaJPanel(userProcessContainer, account, organization, enterprise, business, network));
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error submitting registration: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox cbBloodType;
    private javax.swing.JComboBox cbRequiredOrganType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAntibodyProfile;
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblContraindications;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRequiredOrganType;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreetAddress;
    private javax.swing.JLabel lblTissueMarkers;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUrgencyLevel;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JRadioButton rbCritical;
    private javax.swing.JRadioButton rbHigh;
    private javax.swing.JRadioButton rbMedium;
    private javax.swing.JRadioButton rbStandard;
    private javax.swing.JTextArea txtAreaContraindications;
    private javax.swing.JTextField txtAntibodyProfile;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreetAddress;
    private javax.swing.JTextField txtTissueMarkers;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
