/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GovernmentAgentRole;

/**
 *
 * @author Ing-Ruei
 */

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.GovernmentOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.JOptionPane; // Added import for JOptionPane


public class GovernmentCoordinatorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GovernmentCoordinatorWorkAreaJPanel
     */
    
    private UserAccount userAccount;
    private GovernmentOrganization govtorganization;
    boolean a = true;
    private Enterprise enterprise;
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private Network network;
    
    
    public GovernmentCoordinatorWorkAreaJPanel(UserAccount account, GovernmentOrganization govtorganization, Enterprise enterprise, EcoSystem business, Network network) {
        initComponents();
        this.userAccount = account;
        this.govtorganization = govtorganization;
        this.enterprise = enterprise;
        this.system = business;
        this.network = network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);    
    }
    
    public void clickmenu(JPanel h1, JPanel h2, int numberbool){
        
        if(numberbool == 1){
            
            h1.setBackground(new Color(70,55,37));
            h2.setBackground(new Color(216,99,1));        
        }
        else{
            h1.setBackground(new Color(216,99,1));
            h2.setBackground(new Color(70,55,37));   
        }  
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        btnDetectSuspiciousActivity = new javax.swing.JLabel(); // Added
        btnViewAntiTraffickingAlerts = new javax.swing.JLabel(); // Added
        userProcessContainer = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(0, 102, 102));
        Header.setForeground(new java.awt.Color(204, 255, 204));
        Header.setPreferredSize(new java.awt.Dimension(800, 50));
        Header.setLayout(new java.awt.GridLayout(1, 0));

        btnDetectSuspiciousActivity.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDetectSuspiciousActivity.setForeground(new java.awt.Color(204, 255, 204));
        btnDetectSuspiciousActivity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDetectSuspiciousActivity.setText("Detect Suspicious Activity");
        btnDetectSuspiciousActivity.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDetectSuspiciousActivity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDetectSuspiciousActivityMouseClicked(evt);
            }
        });
        Header.add(btnDetectSuspiciousActivity);

        btnViewAntiTraffickingAlerts.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnViewAntiTraffickingAlerts.setForeground(new java.awt.Color(204, 255, 204));
        btnViewAntiTraffickingAlerts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnViewAntiTraffickingAlerts.setText("View Anti-Trafficking Alerts");
        btnViewAntiTraffickingAlerts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewAntiTraffickingAlerts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewAntiTraffickingAlertsMouseClicked(evt);
            }
        });
        Header.add(btnViewAntiTraffickingAlerts);

        add(Header, java.awt.BorderLayout.PAGE_START);

        userProcessContainer.setBackground(new java.awt.Color(0, 153, 153));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        add(userProcessContainer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetectSuspiciousActivityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetectSuspiciousActivityMouseClicked
        system.detectSuspiciousActivity();
        JOptionPane.showMessageDialog(this, "Suspicious activity detection initiated. Check alerts!", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDetectSuspiciousActivityMouseClicked

    private void btnViewAntiTraffickingAlertsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAntiTraffickingAlertsMouseClicked
        // TODO: Navigate to ViewAntiTraffickingAlertsJPanel
        // Example:
        // ViewAntiTraffickingAlertsJPanel viewAlertsJPanel = new ViewAntiTraffickingAlertsJPanel(userProcessContainer, system, govtorganization);
        // userProcessContainer.add("ViewAntiTraffickingAlertsJPanel", viewAlertsJPanel);
        // CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        // layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewAntiTraffickingAlertsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel btnDetectSuspiciousActivity;
    private javax.swing.JLabel btnViewAntiTraffickingAlerts;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}


