package userinterface.GovernmentAgentRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;

public class InternationalAffairsOfficerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private Network network;

    /**
     * Creates new form InternationalAffairsOfficerWorkAreaJPanel
     */
    public InternationalAffairsOfficerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.network = network;
        
        lblWelcome.setText("Welcome International Affairs Officer " + account.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        btnManageRegulatoryCoordination = new javax.swing.JButton();
        btnManageInternationalPartnerships = new javax.swing.JButton();
        btnOverseeCrossBorderExchange = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        lblWelcome.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(204, 255, 204));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome International Affairs Officer!");

        btnManageRegulatoryCoordination.setBackground(new java.awt.Color(0, 102, 102));
        btnManageRegulatoryCoordination.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnManageRegulatoryCoordination.setForeground(new java.awt.Color(204, 255, 204));
        btnManageRegulatoryCoordination.setText("Manage Regulatory Coordination");
        btnManageRegulatoryCoordination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRegulatoryCoordinationActionPerformed(evt);
            }
        });

        btnManageInternationalPartnerships.setBackground(new java.awt.Color(0, 102, 102));
        btnManageInternationalPartnerships.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnManageInternationalPartnerships.setForeground(new java.awt.Color(204, 255, 204));
        btnManageInternationalPartnerships.setText("Manage International Partnerships");
        btnManageInternationalPartnerships.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageInternationalPartnershipsActionPerformed(evt);
            }
        });

        btnOverseeCrossBorderExchange.setBackground(new java.awt.Color(0, 102, 102));
        btnOverseeCrossBorderExchange.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnOverseeCrossBorderExchange.setForeground(new java.awt.Color(204, 255, 204));
        btnOverseeCrossBorderExchange.setText("Oversee Cross-Border Organ Exchange");
        btnOverseeCrossBorderExchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOverseeCrossBorderExchangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOverseeCrossBorderExchange, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageInternationalPartnerships, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageRegulatoryCoordination, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblWelcome)
                .addGap(80, 80, 80)
                .addComponent(btnManageRegulatoryCoordination, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageInternationalPartnerships, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOverseeCrossBorderExchange, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(285, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageRegulatoryCoordinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRegulatoryCoordinationActionPerformed
        // TODO: Implement logic for managing regulatory coordination
    }//GEN-LAST:event_btnManageRegulatoryCoordinationActionPerformed

    private void btnManageInternationalPartnershipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageInternationalPartnershipsActionPerformed
        // TODO: Implement logic for managing international partnerships
    }//GEN-LAST:event_btnManageInternationalPartnershipsActionPerformed

    private void btnOverseeCrossBorderExchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOverseeCrossBorderExchangeActionPerformed
        // TODO: Implement logic for overseeing cross-border organ exchange
    }//GEN-LAST:event_btnOverseeCrossBorderExchangeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageInternationalPartnerships;
    private javax.swing.JButton btnManageRegulatoryCoordination;
    private javax.swing.JButton btnOverseeCrossBorderExchange;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
