package userinterface.GovernmentAgentRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.GovernmentOrganization;
import Business.Requests.AntiTraffickingAlert;
import Business.Statuses.RequestStatus;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class ViewAntiTraffickingAlertsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount account;
    private GovernmentOrganization governmentOrganization;

    /**
     * Creates new form ViewAntiTraffickingAlertsJPanel
     */
    public ViewAntiTraffickingAlertsJPanel(JPanel userProcessContainer, EcoSystem system, UserAccount account, GovernmentOrganization governmentOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;
        this.governmentOrganization = governmentOrganization;
        
        populateAlertTable();
    }
    
    public void populateAlertTable() {
        DefaultTableModel model = (DefaultTableModel) tblAlerts.getModel();
        model.setRowCount(0);
        
        for (WorkRequest request : governmentOrganization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof AntiTraffickingAlert) {
                AntiTraffickingAlert alert = (AntiTraffickingAlert) request;
                Object[] row = new Object[6];
                row[0] = alert; // The AntiTraffickingAlert object itself
                row[1] = alert.getSuspectedActivity();
                row[2] = alert.getRelatedEntity();
                row[3] = alert.getGeographicalArea();
                row[4] = alert.getAlertLevel();
                row[5] = alert.getStatus();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlerts = new javax.swing.JTable();
        btnMarkAsReviewed = new javax.swing.JButton();
        btnResolveAlert = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 255, 204));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Anti-Trafficking Alerts");

        tblAlerts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Alert ID", "Activity", "Related Entity", "Location", "Level", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAlerts);

        btnMarkAsReviewed.setBackground(new java.awt.Color(0, 102, 102));
        btnMarkAsReviewed.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMarkAsReviewed.setForeground(new java.awt.Color(204, 255, 204));
        btnMarkAsReviewed.setText("Mark as Reviewed");
        btnMarkAsReviewed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkAsReviewedActionPerformed(evt);
            }
        });

        btnResolveAlert.setBackground(new java.awt.Color(0, 102, 102));
        btnResolveAlert.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnResolveAlert.setForeground(new java.awt.Color(204, 255, 204));
        btnResolveAlert.setText("Resolve Alert");
        btnResolveAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolveAlertActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(204, 255, 204));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(222, 222, 222)
                                .addComponent(btnMarkAsReviewed)
                                .addGap(18, 18, 18)
                                .addComponent(btnResolveAlert))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 71, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMarkAsReviewed)
                    .addComponent(btnResolveAlert)
                    .addComponent(btnBack))
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnMarkAsReviewedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkAsReviewedActionPerformed
        int selectedRow = tblAlerts.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an alert to mark as reviewed.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        AntiTraffickingAlert alert = (AntiTraffickingAlert) tblAlerts.getValueAt(selectedRow, 0);
        if (alert.getStatus().equals("Reviewed") || alert.getStatus().equals("Resolved")) {
            JOptionPane.showMessageDialog(this, "Alert has already been reviewed or resolved.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        alert.setStatus("Reviewed");
        alert.setReceiver(account); // Assign to the current government agent
        alert.setResolveDate(new Date());
        JOptionPane.showMessageDialog(this, "Alert marked as reviewed.", "Success", JOptionPane.INFORMATION_MESSAGE);
        populateAlertTable();
    }//GEN-LAST:event_btnMarkAsReviewedActionPerformed

    private void btnResolveAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolveAlertActionPerformed
        int selectedRow = tblAlerts.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an alert to resolve.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        AntiTraffickingAlert alert = (AntiTraffickingAlert) tblAlerts.getValueAt(selectedRow, 0);
        if (alert.getStatus().equals("Resolved")) {
            JOptionPane.showMessageDialog(this, "Alert has already been resolved.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        alert.setStatus("Resolved");
        alert.setReceiver(account); // Assign to the current government agent
        alert.setResolveDate(new Date());
        JOptionPane.showMessageDialog(this, "Alert resolved.", "Success", JOptionPane.INFORMATION_MESSAGE);
        populateAlertTable();
    }//GEN-LAST:event_btnResolveAlertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMarkAsReviewed;
    private javax.swing.JButton btnResolveAlert;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblAlerts;
    // End of variables declaration//GEN-END:variables
}
