/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LogisticsOfficerRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.LogisticsOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout; // Added import
import java.awt.Color;
import javax.swing.JPanel;
import userinterface.LogisticsOfficerRole.ManageOrganLogisticsJPanel; // Added import


/**
 *
 * @author Ing-Ruei
 */
public class LogisticsOfficerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LogisticsOfficerWorkAreaJPanel
     */
    
    private UserAccount userAccount;
    boolean a = true;
    private LogisticsOrganization legalofficerorganization;
    private Enterprise enterprise;
    private EcoSystem system;
    private Network network;
    
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public LogisticsOfficerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, LogisticsOrganization legalofficerorganization, Enterprise enterprise, EcoSystem business, Network network) {
        this.userProcessContainer = userProcessContainer; // Assign the passed userProcessContainer
        initComponents();
        this.system = system;
        this.userAccount = account;
        this.legalofficerorganization = legalofficerorganization;
        this.enterprise = enterprise;
        this.system = business;
        this.network = network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);    
    }
    
    public void clickmenu(JPanel h1, JPanel h2, int numberbool){
        
        if(numberbool == 1){
            
            h1.setBackground(new Color(70,55,37));
            h2.setBackground(new Color(216,99,1));        
        }
        else{
            h1.setBackground(new Color(216,99,1));
            h2.setBackground(new Color(70,55,37));   
        }  
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        btnManageOrganLogistics = new javax.swing.JLabel(); // Declaration moved

        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(0, 102, 102));
        Header.setPreferredSize(new java.awt.Dimension(800, 50));
        Header.setLayout(new java.awt.GridLayout(1, 0));

        btnManageOrganLogistics.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnManageOrganLogistics.setForeground(new java.awt.Color(255, 255, 255));
        btnManageOrganLogistics.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnManageOrganLogistics.setText("Manage Organ Logistics");
        btnManageOrganLogistics.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageOrganLogistics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManageOrganLogisticsMouseClicked(evt);
            }
        });
        Header.add(btnManageOrganLogistics);

        add(Header, java.awt.BorderLayout.PAGE_START);

        userProcessContainer.setBackground(new java.awt.Color(0, 153, 153));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        add(userProcessContainer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents



    private void btnManageOrganLogisticsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageOrganLogisticsMouseClicked
        ManageOrganLogisticsJPanel manageOrganLogisticsJPanel = new ManageOrganLogisticsJPanel(userProcessContainer, userAccount, legalofficerorganization, enterprise, system, network);
        userProcessContainer.add("ManageOrganLogisticsJPanel", manageOrganLogisticsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageOrganLogisticsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel btnManageOrganLogistics;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
