package userinterface.LogisticsOfficerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise; // Added import
import Business.Network.Network;
import Business.Organization.LogisticsOrganization;
import Business.Organization.Organization; // Added import
import Business.Requests.LogisticsRequest;
import Business.Requests.SurgeryRequest; // Added import
import Business.Statuses.RequestStatus;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane; // Added import
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class ManageOrganLogisticsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private LogisticsOrganization logisticsOrganization;
    private Enterprise enterprise;
    private EcoSystem business;
    private Network network;

    /**
     * Creates new form ManageOrganLogisticsJPanel
     */
    public ManageOrganLogisticsJPanel(JPanel userProcessContainer, UserAccount account, LogisticsOrganization logisticsOrganization, Enterprise enterprise, EcoSystem business, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.logisticsOrganization = logisticsOrganization;
        this.enterprise = enterprise;
        this.business = business;
        this.network = network;
        
        populateRequestTable();
    }
    
    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) tblLogisticsRequests.getModel();
        model.setRowCount(0);
        
        for (WorkRequest request : logisticsOrganization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof LogisticsRequest) {
                LogisticsRequest logisticsRequest = (LogisticsRequest) request;
                Object[] row = new Object[7];
                row[0] = logisticsRequest; // The LogisticsRequest object itself
                row[1] = logisticsRequest.getOrganMatch().getPatientRequest().getPatient().getName();
                row[2] = logisticsRequest.getOrganMatch().getDonorRequest().getDonor().getName();
                row[3] = logisticsRequest.getOrganMatch().getPatientRequest().getRequiredOrganType();
                row[4] = logisticsRequest.getStatus();
                row[5] = logisticsRequest.getReceiver() == null ? "Not Assigned" : logisticsRequest.getReceiver().getEmployee().getName();
                row[6] = logisticsRequest.getRequestDate();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLogisticsRequests = new javax.swing.JTable();
        btnAssignToMe = new javax.swing.JButton();
        btnUpdateStatus = new javax.swing.JButton();
        btnSimulateQRScan = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblTrackingNumber = new javax.swing.JLabel();
        txtTrackingNumber = new javax.swing.JTextField();
        lblCurrentLocation = new javax.swing.JLabel();
        txtCurrentLocation = new javax.swing.JTextField();
        lblPreservationCondition = new javax.swing.JLabel();
        txtPreservationCondition = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 255, 204));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Organ Logistics");

        tblLogisticsRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Patient", "Donor", "Organ", "Status", "Assigned To", "Request Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLogisticsRequests);

        btnAssignToMe.setBackground(new java.awt.Color(0, 102, 102));
        btnAssignToMe.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAssignToMe.setForeground(new java.awt.Color(204, 255, 204));
        btnAssignToMe.setText("Assign to Me");
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });

        btnUpdateStatus.setBackground(new java.awt.Color(0, 102, 102));
        btnUpdateStatus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnUpdateStatus.setForeground(new java.awt.Color(204, 255, 204));
        btnUpdateStatus.setText("Update Status");
        btnUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStatusActionPerformed(evt);
            }
        });

        btnSimulateQRScan.setBackground(new java.awt.Color(0, 102, 102));
        btnSimulateQRScan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSimulateQRScan.setForeground(new java.awt.Color(204, 255, 204));
        btnSimulateQRScan.setText("Simulate QR Scan");
        btnSimulateQRScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimulateQRScanActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(204, 255, 204));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTrackingNumber.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTrackingNumber.setForeground(new java.awt.Color(204, 255, 204));
        lblTrackingNumber.setText("Tracking Number:");

        lblCurrentLocation.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCurrentLocation.setForeground(new java.awt.Color(204, 255, 204));
        lblCurrentLocation.setText("Current Location:");

        lblPreservationCondition.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPreservationCondition.setForeground(new java.awt.Color(204, 255, 204));
        lblPreservationCondition.setText("Preservation Condition:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(18, 18, 18)
                        .addComponent(btnAssignToMe)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateStatus)
                        .addGap(18, 18, 18)
                        .addComponent(btnSimulateQRScan))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTrackingNumber)
                            .addGap(18, 18, 18)
                            .addComponent(txtTrackingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblCurrentLocation)
                            .addGap(18, 18, 18)
                            .addComponent(txtCurrentLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblPreservationCondition)
                            .addGap(18, 18, 18)
                            .addComponent(txtPreservationCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssignToMe)
                    .addComponent(btnUpdateStatus)
                    .addComponent(btnSimulateQRScan)
                    .addComponent(btnBack))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrackingNumber)
                    .addComponent(txtTrackingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentLocation)
                    .addComponent(txtCurrentLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreservationCondition)
                    .addComponent(txtPreservationCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed
        int selectedRow = tblLogisticsRequests.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request to assign.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        LogisticsRequest request = (LogisticsRequest) tblLogisticsRequests.getValueAt(selectedRow, 0);
        if (!request.getStatus().equals(RequestStatus.OrganLogisticsStatus.RETRIEVAL_SCHEDULED.getValue())) {
            JOptionPane.showMessageDialog(this, "Request is not in 'Retrieval Scheduled' status and cannot be assigned.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        request.setReceiver(account);
        request.setStatus(RequestStatus.OrganLogisticsStatus.RETRIEVAL_STARTED.getValue());
        JOptionPane.showMessageDialog(this, "Request assigned to you. Status updated to 'Retrieval Started'.", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        // Notify the Case Manager (sender of the LogisticsRequest)
        EcoSystem.sendNotification(request.getSender(), "Your Logistics Request for Match ID: " + request.getOrganMatch().getMatchId() + " has been assigned to Logistics Officer " + account.getUsername() + " and retrieval has started.");
        
        populateRequestTable();
    }//GEN-LAST:event_btnAssignToMeActionPerformed

    private void btnUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusActionPerformed
        int selectedRow = tblLogisticsRequests.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request to update.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        LogisticsRequest request = (LogisticsRequest) tblLogisticsRequests.getValueAt(selectedRow, 0);
        if (request.getReceiver() == null || !request.getReceiver().equals(account)) {
            JOptionPane.showMessageDialog(this, "Request is not assigned to you.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String newStatus = JOptionPane.showInputDialog(this, "Enter new status (e.g., In Transit, Delivered):");
        if (newStatus != null && !newStatus.trim().isEmpty()) {
            request.setStatus(newStatus.trim());
            request.setCurrentOrganLocation(txtCurrentLocation.getText());
            request.setPreservationCondition(txtPreservationCondition.getText());
            request.setTrackingNumber(txtTrackingNumber.getText());
            request.setResolveDate(new Date());
            
            // Notify the Case Manager (sender of the LogisticsRequest) about the status update
            EcoSystem.sendNotification(request.getSender(), "Logistics Request for Match ID: " + request.getOrganMatch().getMatchId() + " has been updated to: " + newStatus.trim());

            if (newStatus.trim().equalsIgnoreCase(RequestStatus.OrganLogisticsStatus.DELIVERED.getValue())) {
                request.getOrganMatch().setStatus(RequestStatus.OrganLogisticsStatus.DELIVERED.getValue()); // Update OrganMatch status
                
                // Route to next stage for Transplant Surgery & Post-Op Reporting
                SurgeryRequest surgeryRequest = new SurgeryRequest(request.getOrganMatch());
                surgeryRequest.setSender(account); // Logistics Officer sending the request to the doctor
                surgeryRequest.setStatus(RequestStatus.SurgeryStatus.SCHEDULED.getValue());
                
                // Find the TransplantClinicOrganization to route the surgery request to
                Organization transplantClinicOrganization = null;
                for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) { // Assuming single network for now
                    if (e.getEnterpriseType() == Enterprise.EnterpriseType.TransplantCenter) { // Assuming TransplantCenterEnterprise manages TransplantClinicOrganization
                        for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
                            if (org.getType() == Organization.Type.TransplantClinic) {
                                transplantClinicOrganization = org;
                                break;
                            }
                        }
                    }
                    if (transplantClinicOrganization != null) {
                        break;
                    }
                }

                if (transplantClinicOrganization != null) {
                    transplantClinicOrganization.getWorkQueue().addWorkRequest(surgeryRequest);
                    request.getOrganMatch().setStatus(RequestStatus.SurgeryStatus.SCHEDULED.getValue()); // Update OrganMatch status
                    JOptionPane.showMessageDialog(this, "Organ delivered! Surgery request sent to Transplant Clinic.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    
                    // Notify the Transplant Coordinator
                    UserAccount transplantCoordinatorAccount = null;
                    for (Network net : business.getNetworkList()) { // Iterate through all networks
                        for (Enterprise ent : net.getEnterpriseDirectory().getEnterpriseList()) {
                            for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()) {
                                if (organization.getType() == Organization.Type.TransplantClinic) { // Assuming this is the TransplantCoordinatorOrganization
                                    for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
                                        if (ua.getRole() instanceof Business.Role.TransplantCoordinatorRole) {
                                            transplantCoordinatorAccount = ua;
                                            break;
                                        }
                                    }
                                }
                                if (transplantCoordinatorAccount != null) break;
                            }
                            if (transplantCoordinatorAccount != null) break;
                        }
                        if (transplantCoordinatorAccount != null) break;
                    }

                    if (transplantCoordinatorAccount != null) {
                        EcoSystem.sendNotification(transplantCoordinatorAccount, "Organ for Match ID: " + request.getOrganMatch().getMatchId() + " has been delivered and surgery request sent to Transplant Clinic.");
                    } else {
                        System.err.println("No Transplant Coordinator found to send notification.");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "No Transplant Clinic Organization found to process the surgery request.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            JOptionPane.showMessageDialog(this, "Request status updated to " + newStatus.trim() + ".", "Success", JOptionPane.INFORMATION_MESSAGE);
            populateRequestTable();
        } else {
            JOptionPane.showMessageDialog(this, "New status cannot be empty.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateStatusActionPerformed

    private void btnSimulateQRScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimulateQRScanActionPerformed
        int selectedRow = tblLogisticsRequests.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request to simulate QR scan for.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        LogisticsRequest request = (LogisticsRequest) tblLogisticsRequests.getValueAt(selectedRow, 0);
        if (request.getReceiver() == null || !request.getReceiver().equals(account)) {
            JOptionPane.showMessageDialog(this, "Request is not assigned to you.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Simulate QR scan and update chain of custody
        request.setQrCodeScanStatus("Scanned at " + new Date());
        JOptionPane.showMessageDialog(this, "QR Code scanned successfully for request: " + request.getOrganMatch().getMatchId(), "Success", JOptionPane.INFORMATION_MESSAGE);
        // Notify the Case Manager (sender of the LogisticsRequest) about the QR scan
        EcoSystem.sendNotification(request.getSender(), "Logistics Request for Match ID: " + request.getOrganMatch().getMatchId() + ": Organ scanned at " + request.getQrCodeScanStatus());
        populateRequestTable();
    }//GEN-LAST:event_btnSimulateQRScanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSimulateQRScan;
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurrentLocation;
    private javax.swing.JLabel lblPreservationCondition;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTrackingNumber;
    private javax.swing.JTable tblLogisticsRequests;
    private javax.swing.JTextField txtCurrentLocation;
    private javax.swing.JTextField txtPreservationCondition;
    private javax.swing.JTextField txtTrackingNumber;
    // End of variables declaration//GEN-END:variables
}
