/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HomePages;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Role.DonorRole;
import Business.Role.RecipientRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author wanyu
 */
public class CreateAccountJPanel extends javax.swing.JPanel {
    
    private EcoSystem system;
    private JPanel mainProcessContainer;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    /**
     * Creates new form CreateAccountJPanel
     */
    public CreateAccountJPanel(EcoSystem system, JPanel mainProcessContainer) {
        initComponents();
        
        this.system = system;
        this.mainProcessContainer = mainProcessContainer;
             // 初始化角色下拉選單
        cmbRole.removeAllItems();
        cmbRole.addItem("Donor");
        cmbRole.addItem("Recipient");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        cmbRole = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPassWord = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();

        btnCreate.setText("Create Acoount");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        jLabel3.setText("Create an account");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Donor", "Receipient" }));

        jLabel4.setText("Role:");

        jLabel1.setText("UserName :");

        jLabel2.setText("Password :");

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(56, 56, 56)
                                    .addComponent(txtPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(77, 77, 77)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBack)
                                    .addComponent(jLabel3))
                                .addGap(178, 178, 178))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(btnCreate)))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(84, 84, 84)
                .addComponent(btnCreate)
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        
        String selectedRole = (String) cmbRole.getSelectedItem();
        String username = txtUserName.getText().trim();
        String password =txtPassWord.getText().trim();
        
        // Validation
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please fill in all fields!", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (selectedRole == null) {
            JOptionPane.showMessageDialog(this, 
                "Please select a role!", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            // Find the Third Party Enterprise and Organization
            Enterprise thirdPartyEnterprise = null;
            Organization targetOrg = null;
            
            for (Business.Network.Network network : system.getNetworkList()) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.ThirdParty) {
                        thirdPartyEnterprise = enterprise;
                        // Find the ThirdParty organization
                        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                            if (org.getType() == Organization.Type.ThirdParty) {
                                targetOrg = org;
                                break;
                            }
                        }
                        break;
                    }
                }
                if (thirdPartyEnterprise != null) break;
            }
            
            if (targetOrg == null) {
                JOptionPane.showMessageDialog(this, 
                    "System configuration error: No organization found!", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Check if username already exists in this organization
            boolean usernameExists = false;
            for (UserAccount ua : targetOrg.getUserAccountDirectory().getUserAccountList()) {
                if (ua.getUsername().equals(username)) {
                    usernameExists = true;
                    break;
                }
            }
            
            if (usernameExists) {
                JOptionPane.showMessageDialog(this, 
                    "Username already exists! Please choose another.", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Create employee and user account based on selected role
            Employee employee = targetOrg.getEmployeeDirectory().createEmployee(username);
            UserAccount userAccount = null;
            
            if (selectedRole.equals("Donor")) {
                userAccount = targetOrg.getUserAccountDirectory()
                    .createUserAccount(username, password, employee, new DonorRole());
            } else if (selectedRole.equals("Recipient")) {
                userAccount = targetOrg.getUserAccountDirectory()
                    .createUserAccount(username, password, employee, new RecipientRole());
            }
            
            // Save to database
            dB4OUtil.storeSystem(system);
            
            if (userAccount != null) {
                JOptionPane.showMessageDialog(this, 
                    selectedRole + " account created successfully!\nPlease login with your credentials.", 
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
                
                // Clear fields
              
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Failed to create account. Please try again.", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
            
            } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error creating account: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
                                                    
        
          // Clear fields
          txtUserName.setText("");
          txtPassWord.setText("");
          cmbRole.setSelectedIndex(0);
          
          // Return to login page
          returnToLogin();
    }                                         

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
          returnToLogin();
    }//GEN-LAST:event_btnBackActionPerformed
    
    private void returnToLogin() {
        mainProcessContainer.removeAll();
        mainProcessContainer.add("LoginJPanel", new LoginJPanel(system, mainProcessContainer));
        CardLayout layout = (CardLayout) mainProcessContainer.getLayout();
        layout.next(mainProcessContainer);
    }

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtPassWord;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
