package userinterface.CommonPanels;

import Business.EcoSystem;
import Business.OrganMatch;
import Business.Statuses.RequestStatus;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class EmergencyDashboardJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    // Potentially an EmergencyRequest or similar object to manage the ongoing emergency
    private OrganMatch activeEmergencyMatch; // If an emergency is tied to a specific match

    /**
     * Creates new form EmergencyDashboardJPanel
     */
    public EmergencyDashboardJPanel(JPanel userProcessContainer, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        
        // Populate a table with any active emergency requests or relevant matches
        populateEmergencyTable();
    }
    
    public void populateEmergencyTable() {
        DefaultTableModel model = (DefaultTableModel) tblEmergencyRequests.getModel();
        model.setRowCount(0);
        
        // This example assumes a simple listing of OrganMatches in an emergency status
        // In a real scenario, you'd have an EmergencyRequest class and a directory
        for (OrganMatch match : business.getMatchedRequests()) {
            if (match.getStatus().equalsIgnoreCase(RequestStatus.EmergencyStatus.ISSUE_DETECTED.getValue()) ||
                match.getStatus().equalsIgnoreCase(RequestStatus.EmergencyStatus.ALERT_ESCALATED.getValue()) ||
                match.getStatus().equalsIgnoreCase(RequestStatus.EmergencyStatus.COMMUNICATION_OPEN.getValue())) {
                
                Object[] row = new Object[5];
                row[0] = match; // The OrganMatch object itself
                row[1] = match.getPatientRequest().getPatient().getName();
                row[2] = match.getDonorRequest().getDonor().getName();
                row[3] = match.getStatus();
                row[4] = match.getMatchDate(); // Using match date as emergency start date for simplicity
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmergencyRequests = new javax.swing.JTable();
        btnDetectIssue = new javax.swing.JButton();
        btnEscalateAlert = new javax.swing.JButton();
        btnOpenCommunication = new javax.swing.JButton();
        btnDecideContingency = new javax.swing.JButton();
        btnLogDecision = new javax.swing.JButton();
        btnCompleteReview = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 255, 204));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Emergency Dashboard");

        tblEmergencyRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Match ID", "Patient", "Donor", "Status", "Trigger Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmergencyRequests);

        btnDetectIssue.setBackground(new java.awt.Color(0, 102, 102));
        btnDetectIssue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDetectIssue.setForeground(new java.awt.Color(204, 255, 204));
        btnDetectIssue.setText("Detect New Issue");
        btnDetectIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetectIssueActionPerformed(evt);
            }
        });

        btnEscalateAlert.setBackground(new java.awt.Color(0, 102, 102));
        btnEscalateAlert.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEscalateAlert.setForeground(new java.awt.Color(204, 255, 204));
        btnEscalateAlert.setText("Escalate Alert");
        btnEscalateAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscalateAlertActionPerformed(evt);
            }
        });

        btnOpenCommunication.setBackground(new java.awt.Color(0, 102, 102));
        btnOpenCommunication.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnOpenCommunication.setForeground(new java.awt.Color(204, 255, 204));
        btnOpenCommunication.setText("Open Communication Channel");
        btnOpenCommunication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenCommunicationActionPerformed(evt);
            }
        });

        btnDecideContingency.setBackground(new java.awt.Color(0, 102, 102));
        btnDecideContingency.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDecideContingency.setForeground(new java.awt.Color(204, 255, 204));
        btnDecideContingency.setText("Decide Contingency Action");
        btnDecideContingency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecideContingencyActionPerformed(evt);
            }
        });

        btnLogDecision.setBackground(new java.awt.Color(0, 102, 102));
        btnLogDecision.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLogDecision.setForeground(new java.awt.Color(204, 255, 204));
        btnLogDecision.setText("Log Decision");
        btnLogDecision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogDecisionActionPerformed(evt);
            }
        });

        btnCompleteReview.setBackground(new java.awt.Color(0, 102, 102));
        btnCompleteReview.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCompleteReview.setForeground(new java.awt.Color(204, 255, 204));
        btnCompleteReview.setText("Complete Post-Incident Review");
        btnCompleteReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteReviewActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(204, 255, 204));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDetectIssue)
                        .addGap(18, 18, 18)
                        .addComponent(btnEscalateAlert)
                        .addGap(18, 18, 18)
                        .addComponent(btnOpenCommunication)
                        .addGap(18, 18, 18)
                        .addComponent(btnDecideContingency)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogDecision)
                        .addGap(18, 18, 18)
                        .addComponent(btnCompleteReview))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetectIssue)
                    .addComponent(btnEscalateAlert)
                    .addComponent(btnOpenCommunication)
                    .addComponent(btnDecideContingency)
                    .addComponent(btnLogDecision)
                    .addComponent(btnCompleteReview))
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDetectIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetectIssueActionPerformed
        int selectedRow = tblEmergencyRequests.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a match to report an issue for.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // This is a simplified approach. In a real system, you might create a new EmergencyRequest object
        // and link it to the OrganMatch, then add it to an EmergencyWorkQueue.
        OrganMatch match = (OrganMatch) tblEmergencyRequests.getValueAt(selectedRow, 0);
        match.setStatus(RequestStatus.EmergencyStatus.ISSUE_DETECTED.getValue());
        JOptionPane.showMessageDialog(this, "Issue detected and marked for match: " + match.getMatchId(), "Success", JOptionPane.INFORMATION_MESSAGE);
        populateEmergencyTable();
    }//GEN-LAST:event_btnDetectIssueActionPerformed

    private void btnEscalateAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscalateAlertActionPerformed
        int selectedRow = tblEmergencyRequests.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an emergency to escalate.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        OrganMatch match = (OrganMatch) tblEmergencyRequests.getValueAt(selectedRow, 0);
        match.setStatus(RequestStatus.EmergencyStatus.ALERT_ESCALATED.getValue());
        JOptionPane.showMessageDialog(this, "Alert escalated for match: " + match.getMatchId(), "Success", JOptionPane.INFORMATION_MESSAGE);
        populateEmergencyTable();
    }//GEN-LAST:event_btnEscalateAlertActionPerformed

    private void btnOpenCommunicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenCommunicationActionPerformed
        int selectedRow = tblEmergencyRequests.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an emergency to open communication for.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        OrganMatch match = (OrganMatch) tblEmergencyRequests.getValueAt(selectedRow, 0);
        match.setStatus(RequestStatus.EmergencyStatus.COMMUNICATION_OPEN.getValue());
        JOptionPane.showMessageDialog(this, "Communication channel opened for match: " + match.getMatchId(), "Success", JOptionPane.INFORMATION_MESSAGE);
        // In a real system, this would open a chat or video conference link
        populateEmergencyTable();
    }//GEN-LAST:event_btnOpenCommunicationActionPerformed

    private void btnDecideContingencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecideContingencyActionPerformed
        int selectedRow = tblEmergencyRequests.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an emergency to decide contingency action for.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        OrganMatch match = (OrganMatch) tblEmergencyRequests.getValueAt(selectedRow, 0);
        String action = JOptionPane.showInputDialog(this, "Enter contingency action (e.g., Redirect organ, Abort procedure):");
        if (action != null && !action.trim().isEmpty()) {
            match.setStatus(RequestStatus.EmergencyStatus.CONTINGENCY_DECIDED.getValue());
            // In a real system, this action would trigger further steps
            JOptionPane.showMessageDialog(this, "Contingency action decided for match: " + match.getMatchId() + "\nAction: " + action, "Success", JOptionPane.INFORMATION_MESSAGE);
            populateEmergencyTable();
        } else {
            JOptionPane.showMessageDialog(this, "Contingency action cannot be empty.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDecideContingencyActionPerformed

    private void btnLogDecisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogDecisionActionPerformed
        int selectedRow = tblEmergencyRequests.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an emergency to log a decision for.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        OrganMatch match = (OrganMatch) tblEmergencyRequests.getValueAt(selectedRow, 0);
        String decisionLog = JOptionPane.showInputDialog(this, "Enter decision details to log:");
        if (decisionLog != null && !decisionLog.trim().isEmpty()) {
            // In a real system, this would log to a dedicated audit trail
            JOptionPane.showMessageDialog(this, "Decision logged for match: " + match.getMatchId() + "\nLog: " + decisionLog, "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Decision log cannot be empty.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnLogDecisionActionPerformed

    private void btnCompleteReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteReviewActionPerformed
        int selectedRow = tblEmergencyRequests.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an emergency to complete review for.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        OrganMatch match = (OrganMatch) tblEmergencyRequests.getValueAt(selectedRow, 0);
        match.setStatus(RequestStatus.EmergencyStatus.RESOLVED.getValue());
        JOptionPane.showMessageDialog(this, "Post-incident review completed for match: " + match.getMatchId(), "Success", JOptionPane.INFORMATION_MESSAGE);
        populateEmergencyTable();
    }//GEN-LAST:event_btnCompleteReviewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCompleteReview;
    private javax.swing.JButton btnDecideContingency;
    private javax.swing.JButton btnDetectIssue;
    private javax.swing.JButton btnEscalateAlert;
    private javax.swing.JButton btnLogDecision;
    private javax.swing.JButton btnOpenCommunication;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblEmergencyRequests;
    // End of variables declaration//GEN-END:variables
}
