package userinterface.HospitalOfficerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.HospitalOrganization; // Added import
import Business.UserAccount.UserAccount;
import java.awt.CardLayout; // Added import
import javax.swing.JPanel;

public class HospitalOfficerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private Network network;

    /**
     * Creates new form HospitalOfficerWorkAreaJPanel
     */
    public HospitalOfficerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.network = network;
        
        lblWelcome.setText("Welcome Hospital Officer " + account.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        btnConfirmDocumentation = new javax.swing.JButton();
        btnOverseeEthicalCompliance = new javax.swing.JButton();
        btnForwardCasesToDoctor = new javax.swing.JButton();
        btnManageDonorVerifications = new javax.swing.JButton();
        btnManagePatientVerifications = new javax.swing.JButton(); // Added Patient Verification button

        setBackground(new java.awt.Color(0, 153, 153));

        lblWelcome.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(204, 255, 204));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome Hospital Officer!");

        btnConfirmDocumentation.setBackground(new java.awt.Color(0, 102, 102));
        btnConfirmDocumentation.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnConfirmDocumentation.setForeground(new java.awt.Color(204, 255, 204));
        btnConfirmDocumentation.setText("Confirm Documentation");
        btnConfirmDocumentation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmDocumentationActionPerformed(evt);
            }
        });

        btnOverseeEthicalCompliance.setBackground(new java.awt.Color(0, 102, 102));
        btnOverseeEthicalCompliance.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnOverseeEthicalCompliance.setForeground(new java.awt.Color(204, 255, 204));
        btnOverseeEthicalCompliance.setText("Oversee Ethical Compliance");
        btnOverseeEthicalCompliance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOverseeEthicalComplianceActionPerformed(evt);
            }
        });

        btnForwardCasesToDoctor.setBackground(new java.awt.Color(0, 102, 102));
        btnForwardCasesToDoctor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnForwardCasesToDoctor.setForeground(new java.awt.Color(204, 255, 204));
        btnForwardCasesToDoctor.setText("Forward Approved Cases to Doctor");
        btnForwardCasesToDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForwardCasesToDoctorActionPerformed(evt);
            }
        });

        btnManageDonorVerifications.setBackground(new java.awt.Color(0, 102, 102));
        btnManageDonorVerifications.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnManageDonorVerifications.setForeground(new java.awt.Color(204, 255, 204));
        btnManageDonorVerifications.setText("Manage Donor Verifications");
        btnManageDonorVerifications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDonorVerificationsActionPerformed(evt);
            }
        });

        btnManagePatientVerifications.setBackground(new java.awt.Color(0, 102, 102));
        btnManagePatientVerifications.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnManagePatientVerifications.setForeground(new java.awt.Color(204, 255, 204));
        btnManagePatientVerifications.setText("Manage Patient Verifications");
        btnManagePatientVerifications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePatientVerificationsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManagePatientVerifications, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageDonorVerifications, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnForwardCasesToDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOverseeEthicalCompliance, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmDocumentation, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblWelcome)
                .addGap(80, 80, 80)
                .addComponent(btnConfirmDocumentation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOverseeEthicalCompliance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnForwardCasesToDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageDonorVerifications, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManagePatientVerifications, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmDocumentationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmDocumentationActionPerformed
        // TODO: Implement logic for confirming documentation
    }//GEN-LAST:event_btnConfirmDocumentationActionPerformed

    private void btnOverseeEthicalComplianceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOverseeEthicalComplianceActionPerformed
        // TODO: Implement logic for overseeing ethical compliance
    }//GEN-LAST:event_btnOverseeEthicalComplianceActionPerformed

    private void btnForwardCasesToDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForwardCasesToDoctorActionPerformed
        // TODO: Implement logic for forwarding approved cases to Doctor
    }//GEN-LAST:event_btnForwardCasesToDoctorActionPerformed

    private void btnManageDonorVerificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDonorVerificationsActionPerformed
        ManageDonorVerificationJPanel manageDonorVerificationJPanel = new ManageDonorVerificationJPanel(userProcessContainer, account, (HospitalOrganization) organization, enterprise, business, network);
        userProcessContainer.add("ManageDonorVerificationJPanel", manageDonorVerificationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageDonorVerificationsActionPerformed

    private void btnManagePatientVerificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePatientVerificationsActionPerformed
        ManagePatientVerificationJPanel managePatientVerificationJPanel = new ManagePatientVerificationJPanel(userProcessContainer, account, (HospitalOrganization) organization, enterprise, business, network);
        userProcessContainer.add("ManagePatientVerificationJPanel", managePatientVerificationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManagePatientVerificationsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmDocumentation;
    private javax.swing.JButton btnForwardCasesToDoctor;
    private javax.swing.JButton btnManageDonorVerifications;
    private javax.swing.JButton btnManagePatientVerifications;
    private javax.swing.JButton btnOverseeEthicalCompliance;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
