package userinterface.HospitalOfficerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.HospitalOrganization;
import Business.Requests.DonorRequest;
import Business.Statuses.RequestStatus; // Corrected import to RequestStatus
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class ManageDonorVerificationJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private HospitalOrganization hospitalOrganization;
    private Enterprise enterprise;
    private EcoSystem business;
    private Network network;

    /**
     * Creates new form ManageDonorVerificationJPanel
     */
    public ManageDonorVerificationJPanel(JPanel userProcessContainer, UserAccount account, HospitalOrganization hospitalOrganization, Enterprise enterprise, EcoSystem business, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.hospitalOrganization = hospitalOrganization;
        this.enterprise = enterprise;
        this.business = business;
        this.network = network;
        
        populateRequestTable();
    }
    
    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) tblDonorRequests.getModel();
        model.setRowCount(0);
        
        for (WorkRequest request : hospitalOrganization.getWorkQueue().getWorkRequestList()) {
            if (request instanceof DonorRequest) {
                DonorRequest donorRequest = (DonorRequest) request;
                Object[] row = new Object[6];
                row[0] = donorRequest; // The DonorRequest object itself
                row[1] = donorRequest.getSender().getEmployee().getName();
                row[2] = donorRequest.getDonationType();
                row[3] = donorRequest.getStatus();
                row[4] = donorRequest.getReceiver() == null ? "Not Assigned" : donorRequest.getReceiver().getEmployee().getName();
                row[5] = donorRequest.getRequestDate();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDonorRequests = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnAssignToMe = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 255, 204));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Donor Verification Requests");

        tblDonorRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Donor Name", "Donation Type", "Status", "Assigned To", "Request Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDonorRequests);

        btnApprove.setBackground(new java.awt.Color(0, 102, 102));
        btnApprove.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnApprove.setForeground(new java.awt.Color(204, 255, 204));
        btnApprove.setText("Approve Request");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnReject.setBackground(new java.awt.Color(0, 102, 102));
        btnReject.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnReject.setForeground(new java.awt.Color(204, 255, 204));
        btnReject.setText("Reject Request");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(204, 255, 204));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAssignToMe.setBackground(new java.awt.Color(0, 102, 102));
        btnAssignToMe.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAssignToMe.setForeground(new java.awt.Color(204, 255, 204));
        btnAssignToMe.setText("Assign to Me");
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(222, 222, 222)
                                .addComponent(btnAssignToMe)
                                .addGap(18, 18, 18)
                                .addComponent(btnApprove)
                                .addGap(18, 18, 18)
                                .addComponent(btnReject))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 71, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApprove)
                    .addComponent(btnReject)
                    .addComponent(btnBack)
                    .addComponent(btnAssignToMe))
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        int selectedRow = tblDonorRequests.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request to approve.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DonorRequest request = (DonorRequest) tblDonorRequests.getValueAt(selectedRow, 0);
        if (!request.getStatus().equals(RequestStatus.DonorApplicationStatus.PENDING_REVIEW.getValue()) && !request.getStatus().equals(RequestStatus.DonorApplicationStatus.ADDITIONAL_TESTING_REQUESTED.getValue())) {
            JOptionPane.showMessageDialog(this, "Request is not in a state to be approved.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (request.getReceiver() == null || !request.getReceiver().equals(account)) {
            JOptionPane.showMessageDialog(this, "Request is not assigned to you.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        request.setStatus(RequestStatus.DonorApplicationStatus.APPROVED.getValue());
        request.getDonor().setStatus(RequestStatus.DonorApplicationStatus.ACTIVE_DONOR); // Update donor's status
        request.setResolveDate(new Date());
        JOptionPane.showMessageDialog(this, "Donor request approved.", "Success", JOptionPane.INFORMATION_MESSAGE);
        populateRequestTable();
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        int selectedRow = tblDonorRequests.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request to reject.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DonorRequest request = (DonorRequest) tblDonorRequests.getValueAt(selectedRow, 0);
        if (!request.getStatus().equals(RequestStatus.DonorApplicationStatus.PENDING_REVIEW.getValue()) && !request.getStatus().equals(RequestStatus.DonorApplicationStatus.ADDITIONAL_TESTING_REQUESTED.getValue())) {
            JOptionPane.showMessageDialog(this, "Request is not in a state to be rejected.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (request.getReceiver() == null || !request.getReceiver().equals(account)) {
            JOptionPane.showMessageDialog(this, "Request is not assigned to you.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        request.setStatus(RequestStatus.DonorApplicationStatus.REJECTED.getValue());
        request.getDonor().setStatus(RequestStatus.DonorApplicationStatus.REJECTED); // Update donor's status
        request.setResolveDate(new Date());
        JOptionPane.showMessageDialog(this, "Donor request rejected.", "Success", JOptionPane.INFORMATION_MESSAGE);
        populateRequestTable();
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed
        int selectedRow = tblDonorRequests.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request to assign.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DonorRequest request = (DonorRequest) tblDonorRequests.getValueAt(selectedRow, 0);
        if (!request.getStatus().equals(RequestStatus.DonorApplicationStatus.PENDING_REVIEW.getValue())) {
            JOptionPane.showMessageDialog(this, "Request is not in PENDING_REVIEW status and cannot be assigned.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        request.setReceiver(account);
        request.setStatus(RequestStatus.DonorApplicationStatus.ADDITIONAL_TESTING_REQUESTED.getValue()); // Or another appropriate status for assigned
        JOptionPane.showMessageDialog(this, "Request assigned to you and status updated.", "Success", JOptionPane.INFORMATION_MESSAGE);
        populateRequestTable();
    }//GEN-LAST:event_btnAssignToMeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReject;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblDonorRequests;
    // End of variables declaration//GEN-END:variables
}
