package userinterface.DonorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout; // Added import
import javax.swing.JPanel;

public class DonorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private Network network;

    /**
     * Creates new form DonorWorkAreaJPanel
     */
    public DonorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.network = network;
        
        lblWelcome.setText("Welcome " + account.getEmployee().getName() + " (Donor)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        btnRegisterDonation = new javax.swing.JButton();
        btnViewDonationStatus = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        lblWelcome.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(204, 255, 204));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome Donor!");

        btnRegisterDonation.setBackground(new java.awt.Color(0, 102, 102));
        btnRegisterDonation.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegisterDonation.setForeground(new java.awt.Color(204, 255, 204));
        btnRegisterDonation.setText("Register for Organ Donation");
        btnRegisterDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterDonationActionPerformed(evt);
            }
        });

        btnViewDonationStatus.setBackground(new java.awt.Color(0, 102, 102));
        btnViewDonationStatus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnViewDonationStatus.setForeground(new java.awt.Color(204, 255, 204));
        btnViewDonationStatus.setText("View Donation Status");
        btnViewDonationStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDonationStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewDonationStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterDonation, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblWelcome)
                .addGap(80, 80, 80)
                .addComponent(btnRegisterDonation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewDonationStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterDonationActionPerformed
        RegisterDonorJPanel registerDonorJPanel = new RegisterDonorJPanel(userProcessContainer, account, organization, enterprise, business, network);
        userProcessContainer.add("RegisterDonorJPanel", registerDonorJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRegisterDonationActionPerformed

    private void btnViewDonationStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDonationStatusActionPerformed
        // TODO: Implement logic for viewing donation status
    }//GEN-LAST:event_btnViewDonationStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegisterDonation;
    private javax.swing.JButton btnViewDonationStatus;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
