package userinterface.DonorRole;

import Business.BloodTypes.PersonBloodTypes.BloodType;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.People.Donor;
import Business.Requests.DonorRequest;
import Business.Statuses.RequestStatus;
import Business.UserAccount.UserAccount;
import Business.OrganTypes.OrganType; // Added import
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel; // Added import
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.DonorRole.DonorWorkAreaJPanel;

public class RegisterDonorJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private Network network;

    /**
     * Creates new form RegisterDonorJPanel
     */
    public RegisterDonorJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.network = network;
        
        populateBloodTypeComboBox();
        setupDonationTypeRadioButtons();
    }

    private void populateBloodTypeComboBox() {
        cbBloodType.setModel(new DefaultComboBoxModel(BloodType.values()));
    }
    
    private void populateOrganTypeComboBox() {
        cbOfferedOrganType.setModel(new DefaultComboBoxModel(OrganType.values()));
    }
    
    private void setupDonationTypeRadioButtons() {
        ButtonGroup group = new ButtonGroup();
        group.add(rbLivingDonation);
        group.add(rbPostMortemDonation);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        lblContact = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lblStreetAddress = new javax.swing.JLabel();
        txtStreetAddress = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        lblZipCode = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblBloodType = new javax.swing.JLabel();
        cbBloodType = new javax.swing.JComboBox();
        lblOfferedOrganType = new javax.swing.JLabel(); // Added
        cbOfferedOrganType = new javax.swing.JComboBox(); // Added
        lblDonationType = new javax.swing.JLabel();
        rbLivingDonation = new javax.swing.JRadioButton();
        rbPostMortemDonation = new javax.swing.JRadioButton();
        chkConsent = new javax.swing.JCheckBox();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblMedicalHistory = new javax.swing.JLabel();
        chkBrainInjury = new javax.swing.JCheckBox();
        chkDiabetesBP = new javax.swing.JCheckBox();
        chkBreathingProblem = new javax.swing.JCheckBox();
        lblCancerDate = new javax.swing.JLabel();
        txtCancerDate = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 255, 204));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Donor Registration Form");

        lblName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(204, 255, 204));
        lblName.setText("Name:");

        lblDOB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(204, 255, 204));
        lblDOB.setText("Date of Birth (YYYY-MM-DD):");

        lblContact.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblContact.setForeground(new java.awt.Color(204, 255, 204));
        lblContact.setText("Contact:");

        lblGender.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblGender.setForeground(new java.awt.Color(204, 255, 204));
        lblGender.setText("Gender:");

        lblStreetAddress.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblStreetAddress.setForeground(new java.awt.Color(204, 255, 204));
        lblStreetAddress.setText("Street Address:");

        lblCity.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCity.setForeground(new java.awt.Color(204, 255, 204));
        lblCity.setText("City:");

        lblState.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblState.setForeground(new java.awt.Color(204, 255, 204));
        lblState.setText("State:");

        lblZipCode.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblZipCode.setForeground(new java.awt.Color(204, 255, 204));
        lblZipCode.setText("Zip Code:");

        lblEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(204, 255, 204));
        lblEmail.setText("Email:");

        lblBloodType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblBloodType.setForeground(new java.awt.Color(204, 255, 204));
        lblBloodType.setText("Blood Type:");

        cbBloodType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblDonationType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDonationType.setForeground(new java.awt.Color(204, 255, 204));
        lblDonationType.setText("Donation Type:");

        rbLivingDonation.setBackground(new java.awt.Color(0, 153, 153));
        rbLivingDonation.setForeground(new java.awt.Color(204, 255, 204));
        rbLivingDonation.setText("Living Donation (e.g., Kidney, Partial Liver)");

        rbPostMortemDonation.setBackground(new java.awt.Color(0, 153, 153));
        rbPostMortemDonation.setForeground(new java.awt.Color(204, 255, 204));
        rbPostMortemDonation.setText("Post-Mortem Donation (All Organs)");

        chkConsent.setBackground(new java.awt.Color(0, 153, 153));
        chkConsent.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        chkConsent.setForeground(new java.awt.Color(204, 255, 204));
        chkConsent.setText("I acknowledge and consent to organ donation.");

        btnSubmit.setBackground(new java.awt.Color(0, 102, 102));
        btnSubmit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(204, 255, 204));
        btnSubmit.setText("Submit Registration");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(204, 255, 204));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblMedicalHistory.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMedicalHistory.setForeground(new java.awt.Color(204, 255, 204));
        lblMedicalHistory.setText("Medical History:");

        chkBrainInjury.setBackground(new java.awt.Color(0, 153, 153));
        chkBrainInjury.setForeground(new java.awt.Color(204, 255, 204));
        chkBrainInjury.setText("Brain Injury");

        chkDiabetesBP.setBackground(new java.awt.Color(0, 153, 153));
        chkDiabetesBP.setForeground(new java.awt.Color(204, 255, 204));
        chkDiabetesBP.setText("Diabetes/BP");

        chkBreathingProblem.setBackground(new java.awt.Color(0, 153, 153));
        chkBreathingProblem.setForeground(new java.awt.Color(204, 255, 204));
        chkBreathingProblem.setText("Breathing Problems");

        lblCancerDate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCancerDate.setForeground(new java.awt.Color(204, 255, 204));
        lblCancerDate.setText("Cancer Diagnosed Date (YYYY-MM-DD, if applicable):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCancerDate)
                            .addComponent(lblDonationType)
                            .addComponent(lblMedicalHistory)
                            .addComponent(lblName)
                            .addComponent(lblDOB)
                            .addComponent(lblContact)
                            .addComponent(lblGender)
                            .addComponent(lblStreetAddress)
                            .addComponent(lblCity)
                            .addComponent(lblState)
                            .addComponent(lblZipCode)
                            .addComponent(lblEmail)
                            .addComponent(lblBloodType)
                            .addComponent(lblOfferedOrganType)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnBack)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbLivingDonation)
                            .addComponent(rbPostMortemDonation)
                            .addComponent(chkConsent)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCancerDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkBrainInjury)
                            .addComponent(chkDiabetesBP)
                            .addComponent(chkBreathingProblem))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbOfferedOrganType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE) // Added
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOB)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContact)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreetAddress)
                    .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipCode)
                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloodType)
                    .addComponent(cbBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOfferedOrganType) // Added
                    .addComponent(cbOfferedOrganType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)) // Added
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicalHistory)
                    .addComponent(chkBrainInjury))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkDiabetesBP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBreathingProblem)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCancerDate)
                    .addComponent(txtCancerDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDonationType)
                    .addComponent(rbLivingDonation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbPostMortemDonation)
                .addGap(18, 18, 18)
                .addComponent(chkConsent)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        try {
            // Create a new Donor object and populate its fields from the form
            Donor donor = new Donor();
            // Assuming donor ID is generated elsewhere or not needed here
            donor.setName(txtName.getText());
            donor.setDob(new Date(txtDOB.getText())); // Simple date parsing, needs robust error handling
            donor.setContact(Long.parseLong(txtContact.getText()));
            donor.setGender(txtGender.getText());
            donor.setStreetAddress(txtStreetAddress.getText());
            donor.setCity(txtCity.getText());
            donor.setState(txtState.getText());
            donor.setZipCode(Integer.parseInt(txtZipCode.getText()));
            donor.setEmailID(txtEmail.getText());
            donor.setBloodType((BloodType) cbBloodType.getSelectedItem());
            
            // Medical history
            donor.setBrainInjury(chkBrainInjury.isSelected());
            donor.setDiabitiesBP(chkDiabetesBP.isSelected());
            donor.setBreathingProb(chkBreathingProblem.isSelected());
            if (!txtCancerDate.getText().isEmpty()) {
                donor.setCancerDiagnosedDate(new Date(txtCancerDate.getText()));
            }

            // Set the account's employee (which represents the donor)
            account.setEmployee(donor.createEmployeeFromDonor()); // Need to add createEmployeeFromDonor method in Donor class

            // Create a new DonorRequest
            DonorRequest donorRequest = new DonorRequest();
            donorRequest.setDonationType(rbLivingDonation.isSelected() ? "Living Donation" : "Post-Mortem Donation");
            donorRequest.setConsentAcknowledged(chkConsent.isSelected());
            donorRequest.setOfferedOrganType((OrganType) cbOfferedOrganType.getSelectedItem()); // Set the offered organ type
            donorRequest.setSender(account);
            donorRequest.setStatus(RequestStatus.DonorApplicationStatus.PENDING_REVIEW.getValue());
            donorRequest.setDonor(donor); // Link the donor object to the request

            // Add the donor to the EcoSystem's donor directory
            business.getDonorDirectory().addDonor(donor);
            // Add the donor request to the EcoSystem's donor request directory
            // business.getDonorRequestDirectory().addDonorRequest(donorRequest); // Removed as request will be added to organization's work queue

            // Route the DonorRequest to an appropriate HospitalOrganization for verification
            Organization hospitalOrganization = null;
            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (e.getEnterpriseType() == Enterprise.EnterpriseType.Hospital) {
                    for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
                        if (org.getType() == Organization.Type.Hospital) {
                            hospitalOrganization = org;
                            break;
                        }
                    }
                }
                if (hospitalOrganization != null) {
                    break;
                }
            }

            if (hospitalOrganization != null) {
                hospitalOrganization.getWorkQueue().addWorkRequest(donorRequest);
                JOptionPane.showMessageDialog(this, "Donor registration submitted successfully and sent for verification!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No Hospital Organization found to process the request.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            // Optionally, navigate back to the DonorWorkAreaJPanel or clear the form
            userProcessContainer.removeAll();
            userProcessContainer.add("DonorWorkAreaJPanel", new DonorWorkAreaJPanel(userProcessContainer, account, organization, enterprise, business, network));
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error submitting registration: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox cbBloodType;
    private javax.swing.JComboBox cbOfferedOrganType; // Declared as member variable
    private javax.swing.JCheckBox chkBrainInjury;
    private javax.swing.JCheckBox chkBreathingProblem;
    private javax.swing.JCheckBox chkConsent;
    private javax.swing.JCheckBox chkDiabetesBP;
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblCancerDate;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDonationType;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblMedicalHistory;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOfferedOrganType; // Declared as member variable
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreetAddress;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JRadioButton rbLivingDonation;
    private javax.swing.JRadioButton rbPostMortemDonation;
    private javax.swing.JTextField txtCancerDate;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreetAddress;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}